const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Event = require('../models/Event');
const Attraction = require('../models/Attraction');
const Restaurant = require('../models/Restaurant');

dotenv.config();

const sampleEvents = [
    {
        name: "Euro 2024",
        imageUrl: "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1928000/euro-2024-depophotos-1928725.jpg",
        description: "The 2024 UEFA European Football Championship, commonly referred to as Euro 2024, is set to be a major international football tournament held across Germany. This prestigious event will bring together the top national teams from Europe to compete for the coveted championship title. The tournament will take place in ten cities, including Berlin, Munich, and Hamburg, showcasing some of the most iconic stadiums in the country. Fans can expect thrilling matches, spectacular goals, and unforgettable moments as teams battle it out on the field. Beyond the football, Euro 2024 will also feature a variety of cultural events, fan zones, and activities, creating a vibrant and festive atmosphere throughout the host cities. With its rich history and passionate fanbase, Euro 2024 promises to be an extraordinary celebration of football, uniting supporters from all over the continent in their love for the beautiful game.",
        date: "2024-06-14",
        coordinates: { latitude: 52.5200, longitude: 13.4050 },
        rating: 5,
        location: { city: "Berlin", country: "Germany" },
        reviewCount: 0,
        types: ["Sports"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Oktoberfest",
        imageUrl: "https://th.bing.com/th/id/OIP.gmKcamp1BOE5XzoGnBYaEQHaEk?rs=1&pid=ImgDetMain",
        description: "Oktoberfest is the world's largest Volksfest, combining a massive beer festival and a traveling funfair. Held annually in Munich, Bavaria, Germany, it is a 16- to 18-day folk festival running from mid or late September to the first Sunday in October, with more than six million people from around the world attending the event every year.",
        date: "2024-09-21",
        coordinates: { latitude: 48.1351, longitude: 11.5820 },
        rating: 5,
        location: { city: "Munich", country: "Germany" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
    name: "Munich Film Festival",
    imageUrl: "https://www.film-tv-video.de/wp-content/uploads/2021/07/B_0721_Filmfest_Muenchen_Gasteig_Schild.jpg",
    description: "The Munich Film Festival is one of the most prestigious film festivals in Germany, showcasing a diverse range of international and German films.",
    date: "2024-06-27",
    coordinates: { latitude: 48.1351, longitude: 11.5820 },
    rating: 5,
    location: { city: "Munich", country: "Germany" },
    reviewCount: 0,
    types: ["Festivals"],
    duration: "1-3hr",
    suitability: ["Indoor", "Family-Friendly"],
    reviews: []
  },
  {
    name: "Tollwood Winter Festival",
    imageUrl: "https://th.bing.com/th/id/R.77139366803b795c7dc6054f47514c39?rik=RhZqEoT%2bc7w1Sg&pid=ImgRaw&r=0",
    description: "The Tollwood Winter Festival in Munich is a cultural festival that features a mix of performances, arts, and crafts, along with a vibrant Christmas market.",
    date: "2024-12-01",
    coordinates: { latitude: 48.1351, longitude: 11.5820 },
    rating: 5,
    location: { city: "Munich", country: "Germany" },
    reviewCount: 0,
    types: ["Festivals"],
    duration: "1-3hr",
    suitability: ["Outdoor", "Family-Friendly"],
    reviews: []
  },
  {
    name: "Munich Marathon",
    imageUrl: "https://img1.runnersworld.de/Muenchen-Marathon-2016-inlineImageCOdc-3cbf4d8-38644.jpg",
    description: "The Munich Marathon is an annual running event that attracts participants from all over the world, offering a scenic route through the city.",
    date: "2024-10-13",
    coordinates: { latitude: 48.1351, longitude: 11.5820 },
    rating: 5,
    location: { city: "Munich", country: "Germany" },
    reviewCount: 0,
    types: ["Sports"],
    duration: ">3hr",
    suitability: ["Outdoor", "Family-Friendly"],
    reviews: []
  },
   {
    name: "Berlin International Film Festival",
    imageUrl: "https://blog.boggi.com/wp-content/uploads/2019/02/2014_0483_ORG_cut-W1606.jpg",
    description: "The Berlin International Film Festival, also known as Berlinale, is one of the world's leading film festivals, featuring a wide array of international films.",
    date: "2024-02-15",
    coordinates: { latitude: 52.5200, longitude: 13.4050 },
    rating: 5,
    location: { city: "Berlin", country: "Germany" },
    reviewCount: 0,
    types: ["Festivals"],
    duration: "1-3hr",
    suitability: ["Indoor", "Family-Friendly"],
    reviews: []
  },
  {
    name: "Berlin Marathon",
    imageUrl: "https://th.bing.com/th/id/R.90fff0e61a122475c7542b957b256da3?rik=nHydx9vg8EXdJQ&riu=http%3a%2f%2fwww.wuerfelfunk.de%2fwp-content%2fuploads%2fzy0n1401.jpg&ehk=Rt6mLkFOigPRvvCAPFY%2bngytAczOAwv%2bjoUwMMlboII%3d&risl=1&pid=ImgRaw&r=0",
    description: "The Berlin Marathon is one of the major marathons in the world, known for its fast and flat course, attracting elite and amateur runners alike.",
    date: "2024-09-29",
    coordinates: { latitude: 52.5200, longitude: 13.4050 },
    rating: 5,
    location: { city: "Berlin", country: "Germany" },
    reviewCount: 0,
    types: ["Sports"],
    duration: ">3hr",
    suitability: ["Outdoor", "Family-Friendly"],
    reviews: []
  },
  {
    name: "Festival of Lights",
    imageUrl: "https://th.bing.com/th/id/OIF.gm7A44K2m22yLEtzToc84A?rs=1&pid=ImgDetMain",
    description: "The Festival of Lights transforms Berlin's landmarks and historical monuments into a spectacular display of light art, attracting visitors from around the globe.",
    date: "2024-10-09",
    coordinates: { latitude: 52.5200, longitude: 13.4050 },
    rating: 5,
    location: { city: "Berlin", country: "Germany" },
    reviewCount: 0,
    types: ["Festivals"],
    duration: "1-3hr",
    suitability: ["Outdoor", "Family-Friendly"],
    reviews: []
  },
    {
        name: "Tokyo Olympics 2020",
        imageUrl: "https://th.bing.com/th/id/R.b1413fee00369348e9eb4d0af4d6990b?rik=AP0iDvyAfGXThA&pid=ImgRaw&r=0",
        description: "The Summer Olympic Games in Tokyo will showcase athletes from around the world competing in various sports, promoting international unity and sportsmanship. The event includes a wide range of competitions, ceremonies, and cultural activities, making it a major global event.",
        date: "2020-07-26",
        coordinates: { latitude: 35.6895, longitude: 139.6917 },
        rating: 5,
        location: { city: "Tokyo", country: "Japan" },
        reviewCount: 0,
        types: ["Sports"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Coachella 2024",
        imageUrl: "https://th.bing.com/th/id/OIP.Kcb4lgdgI4hMASCCAY0mEAAAAA?rs=1&pid=ImgDetMain",
        description: "Coachella Valley Music and Arts Festival, commonly referred to as Coachella, is an annual music and arts festival held at the Empire Polo Club in Indio, California. The event features musical performances from various genres, art installations, and sculptures, attracting attendees from all over the world.",
        date: "2024-04-12",
        coordinates: { latitude: 33.6803, longitude: -116.1739 },
        rating: 5,
        location: { city: "Indio", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Carnival of Venice",
        imageUrl: "https://th.bing.com/th/id/OIP.dY0iied0yxSpgtsUfkJnugAAAA?rs=1&pid=ImgDetMain",
        description: "The Carnival of Venice is an annual festival held in Venice, Italy, renowned for its elaborate masks and costumes. The event includes parades, concerts, balls, and other cultural activities, making it a spectacular celebration of Venetian history and traditions.",
        date: "2024-02-08",
        coordinates: { latitude: 45.4408, longitude: 12.3155 },
        rating: 5,
        location: { city: "Venice", country: "Italy" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Edinburgh Festival Fringe",
        imageUrl: "https://th.bing.com/th/id/OIP.UrzubCWtKDu6KG0uJ0xQ1AHaE8?rs=1&pid=ImgDetMain",
        description: "The Edinburgh Festival Fringe is the world's largest arts festival, taking place every August for three weeks in Edinburgh, Scotland. The festival features performances from a wide variety of artists, including theater, comedy, music, and dance, making it a vibrant and eclectic cultural event.",
        date: "2024-08-02",
        coordinates: { latitude: 55.9533, longitude: -3.1883 },
        rating: 5,
        location: { city: "Edinburgh", country: "UK" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Burning Man",
        imageUrl: "https://th.bing.com/th/id/R.dfe2ecd5a0953a6e43aa3ceb978e45da?rik=OFfqoWSMEMuwvw&riu=http%3a%2f%2fstatic2.businessinsider.com%2fimage%2f59a56f6a2488492cf41e9609-2000%2fburning-man-festival-black-rock-city-aerial-view.jpg&ehk=IBGRqcWapE9TfwENp5EYneNtp0DVYBPiaVnuAHr0V7Y%3d&risl=&pid=ImgRaw&r=0",
        description: "Burning Man is an annual event held in the western United States at Black Rock City, a temporary city erected in the Black Rock Desert of northwest Nevada. The event is described as an experiment in community and art, influenced by 10 main principles, including 'radical self-expression' and 'radical self-reliance'.",
        date: "2024-08-25",
        coordinates: { latitude: 40.7864, longitude: -119.2065 },
        rating: 5,
        location: { city: "Black Rock City", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Day of the Dead",
        imageUrl: "https://th.bing.com/th/id/OIP.eDSfEGZFJHJDBq7orYpA4wHaEf?rs=1&pid=ImgDetMain",
        description: "Day of the Dead, or Día de los Muertos, is a Mexican holiday where families remember and honor their deceased loved ones. The celebrations include vibrant parades, decorated altars, and offerings of food and flowers, making it a culturally rich and colorful event.",
        date: "2024-11-01",
        coordinates: { latitude: 19.4326, longitude: -99.1332 },
        rating: 5,
        location: { city: "Mexico City", country: "Mexico" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Mardi Gras",
        imageUrl: "https://th.bing.com/th/id/R.78966cadae10569189cad495473b1fa5?rik=aI5UkqhE7XEROA&pid=ImgRaw&r=0",
        description: "Mardi Gras, also known as Fat Tuesday, is a festival held before Lent, known for its vibrant parades, masquerade balls, and street parties. The celebration in New Orleans is particularly famous, attracting visitors from all over the world to experience its unique blend of culture, music, and cuisine.",
        date: "2024-02-13",
        coordinates: { latitude: 29.9511, longitude: -90.0715 },
        rating: 5,
        location: { city: "New Orleans", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Glastonbury Festival",
        imageUrl: "https://pisco.meaww.com/a7fe2dcf-5eb0-46fb-a083-aa3bf947c1a4.jpg",
        description: "Glastonbury Festival is a five-day festival of contemporary performing arts that takes place in Pilton, Somerset, England. In addition to contemporary music, the festival hosts dance, comedy, theater, circus, cabaret, and other arts, making it one of the largest and most diverse festivals in the world.",
        date: "2024-06-26",
        coordinates: { latitude: 51.1839, longitude: -2.5866 },
        rating: 5,
        location: { city: "Pilton", country: "UK" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "SXSW",
        imageUrl: "https://static-ssl.businessinsider.com/image/562f53a09dd7cc15008c4f73-3000-1981/sxsw-09920.jpg",
        description: "South by Southwest (SXSW) is an annual conglomerate of film, interactive media, and music festivals and conferences that take place in mid-March in Austin, Texas, United States. The event features a wide range of creative activities, including film screenings, musical performances, and panel discussions, attracting artists and professionals from around the world.",
        date: "2024-03-08",
        coordinates: { latitude: 30.2672, longitude: -97.7431 },
        rating: 5,
        location: { city: "Austin", country: "USA" },
        reviewCount: 0,
        types: ["Conferences"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "La Tomatina",
        imageUrl: "https://blog-content.ixigo.com/wp-content/uploads/2018/08/tomatina.jpg",
        description: "La Tomatina is an annual Spanish festival held in the town of Buñol, where participants throw tomatoes at each other. The event, which attracts thousands of participants, is purely for entertainment and fun, making it a unique and memorable experience.",
        date: "2024-08-28",
        coordinates: { latitude: 39.4920, longitude: -0.4191 },
        rating: 5,
        location: { city: "Buñol", country: "Spain" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Holi Festival",
        imageUrl: "https://th.bing.com/th/id/OIP.1sK4XqW8KKgglrdEIk_U2AAAAA?rs=1&pid=ImgDetMain",
        description: "Holi, also known as the Festival of Colors, is a Hindu festival celebrated in India and Nepal. The festival signifies the victory of good over evil and the arrival of spring, and it involves throwing colored powders and water at each other, dancing, and festive celebrations.",
        date: "2024-03-20",
        coordinates: { latitude: 28.6139, longitude: 77.2090 },
        rating: 5,
        location: { city: "Delhi", country: "India" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Cannes Film Festival",
        imageUrl: "https://variety.com/wp-content/uploads/2023/05/GettyImages-1491781818-e1685202756813.jpg",
        description: "The Cannes Film Festival is an annual film festival held in Cannes, France, which previews new films of all genres, including documentaries, from around the world. The festival is known for its glamorous red carpet events, celebrity appearances, and prestigious awards.",
        date: "2024-05-14",
        coordinates: { latitude: 43.5528, longitude: 7.0174 },
        rating: 5,
        location: { city: "Cannes", country: "France" },
        reviewCount: 0,
        types: ["Conferences"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Sundance Film Festival",
        imageUrl: "https://th.bing.com/th/id/R.631a9863b215c30a804bb3f85996d7dd?rik=MVHXhyf3mZGCVg&pid=ImgRaw&r=0",
        description: "The Sundance Film Festival is an annual film festival organized by the Sundance Institute. It is the largest independent film festival in the United States, showcasing a wide range of independent films, documentaries, and shorts, and providing a platform for emerging filmmakers.",
        date: "2024-01-18",
        coordinates: { latitude: 40.6461, longitude: -111.4980 },
        rating: 5,
        location: { city: "Park City", country: "USA" },
        reviewCount: 0,
        types: ["Conferences"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Jazz Fest",
        imageUrl: "https://th.bing.com/th/id/OIP.zFrJTvf4Mi75QUbZuCdpYgAAAA?rs=1&pid=ImgDetMain",
        description: "The New Orleans Jazz & Heritage Festival, often known simply as Jazz Fest, is an annual celebration of the music and culture of New Orleans and Louisiana. The festival features performances by local and international artists, showcasing a wide range of musical genres including jazz, blues, rock, and gospel.",
        date: "2024-04-26",
        coordinates: { latitude: 29.9511, longitude: -90.0715 },
        rating: 5,
        location: { city: "New Orleans", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Tomorrowland",
        imageUrl: "https://th.bing.com/th/id/R.b9eb9a05d386fc22ded9909019aab4f4?rik=4o%2bvee%2fMkoAS%2bA&pid=ImgRaw&r=0",
        description: "Tomorrowland is an annual electronic dance music festival held in Boom, Belgium. It is one of the largest and most notable music festivals in the world, featuring top DJs and artists from the electronic music scene, spectacular stage designs, and a vibrant atmosphere.",
        date: "2024-07-19",
        coordinates: { latitude: 51.0936, longitude: 4.3911 },
        rating: 5,
        location: { city: "Boom", country: "Belgium" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Diwali",
        imageUrl: "https://th.bing.com/th/id/R.a53a766a2e6622bee0b688bd254a1ed3?rik=vjRx1wYD5AMl1Q&pid=ImgRaw&r=0",
        description: "Diwali, the Hindu festival of lights, is celebrated every autumn in India. The festival signifies the victory of light over darkness and good over evil. Celebrations include lighting oil lamps, fireworks, and sharing festive meals with family and friends.",
        date: "2024-11-03",
        coordinates: { latitude: 28.6139, longitude: 77.2090 },
        rating: 5,
        location: { city: "Delhi", country: "India" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Chinese New Year",
        imageUrl: "https://th.bing.com/th/id/R.044f141c1afbea23bb24478777dcaee0?rik=XT830QeJrgiOiw&pid=ImgRaw&r=0",
        description: "Chinese New Year, also known as the Spring Festival, is the most important traditional festival in China. The celebrations last for several days and include family reunions, feasts, lion and dragon dances, fireworks, and the giving of red envelopes with money.",
        date: "2024-02-10",
        coordinates: { latitude: 39.9042, longitude: 116.4074 },
        rating: 5,
        location: { city: "Beijing", country: "China" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Comic-Con",
        imageUrl: "https://th.bing.com/th/id/R.ee8bb62d791df5c8f94c53ef6f10cd50?rik=N2fKXJAWbCxzbA&pid=ImgRaw&r=0",
        description: "Comic-Con International is an annual comic book convention held in San Diego, California. The event features panels, workshops, and exhibits related to comics, films, television, and pop culture, attracting fans and industry professionals from around the world.",
        date: "2024-07-18",
        coordinates: { latitude: 32.7157, longitude: -117.1611 },
        rating: 5,
        location: { city: "San Diego", country: "USA" },
        reviewCount: 0,
        types: ["Conferences"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Indoor"],
        reviews: []
    },
    {
        name: "Wimbledon",
        imageUrl: "https://th.bing.com/th/id/OIP.mfOArACK3u_cop1IRPVwVQHaE3?rs=1&pid=ImgDetMain",
        description: "The Championships, Wimbledon, commonly known as Wimbledon, is the oldest tennis tournament in the world and is widely regarded as the most prestigious. Held at the All England Club in Wimbledon, London, the event features matches on grass courts and draws players and spectators from around the globe.",
        date: "2024-06-24",
        coordinates: { latitude: 51.4344, longitude: -0.2145 },
        rating: 5,
        location: { city: "London", country: "UK" },
        reviewCount: 0,
        types: ["Sports"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Rio Carnival",
        imageUrl: "https://th.bing.com/th/id/OIP.LddEQhaA_jSP23re2fLl9AHaDt?rs=1&pid=ImgDetMain",
        description: "Rio Carnival is the world's largest carnival, held before Lent every year in Rio de Janeiro, Brazil. The event features samba parades, street parties, and vibrant costumes, attracting millions of visitors to experience the lively and colorful celebration.",
        date: "2024-02-16",
        coordinates: { latitude: -22.9068, longitude: -43.1729 },
        rating: 5,
        location: { city: "Rio de Janeiro", country: "Brazil" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Lollapalooza",
        imageUrl: "https://th.bing.com/th/id/R.0ce2f0f4ebf691c63b0d8b89309f8bbc?rik=YIBSJyM0OmlCrA&pid=ImgRaw&r=0",
        description: "Lollapalooza is an annual music festival featuring a wide variety of music genres, including rock, hip hop, and electronic music. Held in Grant Park, Chicago, the festival also includes visual arts, craft booths, and food stalls, creating a diverse and lively atmosphere.",
        date: "2024-08-01",
        coordinates: { latitude: 41.8758, longitude: -87.6186 },
        rating: 5,
        location: { city: "Chicago", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "St. Patrick's Day Parade",
        imageUrl: "https://th.bing.com/th/id/R.9c9ad46dbbc90d6c80482fc2e7f07908?rik=Ls7QHZ2TFxAPNw&pid=ImgRaw&r=0",
        description: "The St. Patrick's Day Parade is a cultural and religious celebration held on 17 March, the traditional death date of Saint Patrick, the foremost patron saint of Ireland. Parades, wearing green attire, and public festivals are common activities, especially in Dublin, Ireland.",
        date: "2024-03-17",
        coordinates: { latitude: 53.3498, longitude: -6.2603 },
        rating: 5,
        location: { city: "Dublin", country: "Ireland" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "The Kentucky Derby",
        imageUrl: "https://th.bing.com/th/id/R.9784525db85d696b0533347111c44b48?rik=3YeBtApJMn%2bUCg&pid=ImgRaw&r=0",
        description: "The Kentucky Derby is a Grade I stakes race for three-year-old Thoroughbreds, held annually in Louisville, Kentucky, United States. The race is one and a quarter miles long and is held on the first Saturday in May, culminating in a two-week-long Kentucky Derby Festival.",
        date: "2024-05-04",
        coordinates: { latitude: 38.2026, longitude: -85.7713 },
        rating: 5,
        location: { city: "Louisville", country: "USA" },
        reviewCount: 0,
        types: ["Sports"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Thanksgiving Day Parade",
        imageUrl: "https://www.gannett-cdn.com/media/2017/11/23/USATODAY/USATODAY/636470355640265452-XXX-Thanksgiving-Parade-rd2521.JPG",
        description: "The Macy's Thanksgiving Day Parade is an annual parade presented by Macy's. The tradition started in 1924, tying it for the second-oldest Thanksgiving parade in the United States along with America's Thanksgiving Parade in Detroit. It features giant balloons, floats, marching bands, and performances.",
        date: "2024-11-28",
        coordinates: { latitude: 40.7128, longitude: -74.0060 },
        rating: 5,
        location: { city: "New York", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Running of the Bulls",
        imageUrl: "https://th.bing.com/th/id/OIP.6KO71KBSgGLuMqLB6N2S6QHaE2?rs=1&pid=ImgDetMain",
        description: "The Running of the Bulls is an annual event that takes place in Pamplona, Spain, during the San Fermín festival. Participants run in front of a small group of bulls that are let loose on the streets, making it an exhilarating and adrenaline-filled experience.",
        date: "2024-07-07",
        coordinates: { latitude: 42.8169, longitude: -1.6432 },
        rating: 5,
        location: { city: "Pamplona", country: "Spain" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Albuquerque International Balloon Fiesta",
        imageUrl: "https://th.bing.com/th/id/OIP.24UVmXbnSrONwyBCx4ncUAHaFj?rs=1&pid=ImgDetMain",
        description: "The Albuquerque International Balloon Fiesta is an annual hot air balloon festival that takes place in Albuquerque, New Mexico. The event is the largest balloon festival in the world, featuring mass ascensions, balloon glows, and various other activities.",
        date: "2024-10-05",
        coordinates: { latitude: 35.0844, longitude: -106.6504 },
        rating: 5,
        location: { city: "Albuquerque", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Gion Matsuri",
        imageUrl: "https://th.bing.com/th/id/OIP.vl0CCoDyR17jc6DuUjsnMAHaE8?rs=1&pid=ImgDetMain",
        description: "Gion Matsuri is an annual festival in Kyoto, Japan. It is one of the most famous festivals in Japan and takes place in the month of July. The festival is centered around the Yasaka Shrine and features grand parades, traditional music, and street performances.",
        date: "2024-07-01",
        coordinates: { latitude: 35.0116, longitude: 135.7681 },
        rating: 5,
        location: { city: "Kyoto", country: "Japan" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Diwali in India",
        imageUrl: "https://th.bing.com/th/id/OIP.LiWokGPXrkMK0WFF96xREQAAAA?rs=1&pid=ImgDetMain",
        description: "Diwali, also known as the Festival of Lights, is celebrated by millions of Hindus, Sikhs, and Jains across the world. The festival signifies the victory of light over darkness and good over evil. Celebrations include lighting oil lamps, fireworks, and sharing festive meals with family and friends.",
        date: "2024-11-12",
        coordinates: { latitude: 28.6139, longitude: 77.2090 },
        rating: 5,
        location: { city: "Delhi", country: "India" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Tour de France",
        imageUrl: "https://th.bing.com/th/id/R.f4e760d97bcf4c1ad185d034c34ef92f?rik=%2fRbHRgTcm2VPvQ&pid=ImgRaw&r=0",
        description: "The Tour de France is an annual men's multiple stage bicycle race primarily held in France, while also occasionally passing through nearby countries. It consists of 21 day-long segments over a 23-day period and covers around 3,500 kilometers.",
        date: "2024-07-06",
        coordinates: { latitude: 48.8566, longitude: 2.3522 },
        rating: 5,
        location: { city: "Paris", country: "France" },
        reviewCount: 0,
        types: ["Sports"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Tokyo Cherry Blossom Festival",
        imageUrl: "https://static.seeker.io/media/img/1/be581a5e-e9f3-41fe-a869-a1d06f0d0ed8-1400.jpg?placeid=2992&name=Meguro%20River,%20Meguro%20River&lat=35.629906&lng=139.714203",
        description: "The Tokyo Cherry Blossom Festival, also known as Hanami, celebrates the beauty of cherry blossoms. The festival includes picnics under the blooming cherry trees, traditional music and dance performances, and various cultural events throughout the city.",
        date: "2024-03-21",
        coordinates: { latitude: 35.6895, longitude: 139.6917 },
        rating: 5,
        location: { city: "Tokyo", country: "Japan" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "New Year's Eve in Times Square",
        imageUrl: "https://th.bing.com/th/id/OIP.LxtbtgZo8b_XwC5kM_7H0AAAAA?rs=1&pid=ImgDetMain",
        description: "New Year's Eve in Times Square is one of the world's most iconic celebrations. Every year, thousands gather in Times Square to watch the ball drop and ring in the new year with music, confetti, and a spectacular fireworks display.",
        date: "2024-12-31",
        coordinates: { latitude: 40.7580, longitude: -73.9855 },
        rating: 5,
        location: { city: "New York", country: "USA" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Sydney New Year's Eve",
        imageUrl: "https://th.bing.com/th/id/OIP.6iQ_iJ0t3umyppDtz09a0QHaEo?rs=1&pid=ImgDetMain",
        description: "Sydney New Year's Eve is a major public event held every year in Sydney, Australia. The event features one of the world's largest and most spectacular fireworks displays, set against the backdrop of the Sydney Harbour Bridge and the Sydney Opera House.",
        date: "2024-12-31",
        coordinates: { latitude: -33.8688, longitude: 151.2093 },
        rating: 5,
        location: { city: "Sydney", country: "Australia" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Egyptian Sun Festival at Abu Simbel",
        imageUrl: "https://th.bing.com/th/id/OIP.xdfBws58IokzRU2kpXozpgHaE7?rs=1&pid=ImgDetMain",
        description: "The Egyptian Sun Festival at Abu Simbel celebrates the phenomenon where the sun illuminates the inner sanctuary of the Great Temple of Ramses II. The event includes traditional music, dance, and cultural performances, attracting visitors from around the world.",
        date: "2024-02-22",
        coordinates: { latitude: 22.3375, longitude: 31.6257 },
        rating: 5,
        location: { city: "Abu Simbel", country: "Egypt" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Cairo International Film Festival",
        imageUrl: "https://th.bing.com/th/id/OIP.-gbw5kfSKhASP3kZcNJcVwHaE7?rs=1&pid=ImgDetMain",
        description: "The Cairo International Film Festival is an annual film festival held in Cairo, Egypt. The event showcases films from around the world, promoting cultural exchange and providing a platform for filmmakers to present their work to an international audience.",
        date: "2024-11-20",
        coordinates: { latitude: 30.0444, longitude: 31.2357 },
        rating: 5,
        location: { city: "Cairo", country: "Egypt" },
        reviewCount: 0,
        types: ["Conferences"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Indoor"],
        reviews: []
    },
    {
        name: "Pyramids Marathon",
        imageUrl: "https://th.bing.com/th/id/OIP.lveWeDYUDBfp9noEP9-TKwHaE7?rs=1&pid=ImgDetMain",
        description: "The Pyramids Marathon is an annual marathon race that takes place in Giza, Egypt. Runners from around the world participate in the event, which features a course that passes by the iconic pyramids, offering a unique and historic backdrop.",
        date: "2024-02-15",
        coordinates: { latitude: 29.9792, longitude: 31.1342 },
        rating: 5,
        location: { city: "Giza", country: "Egypt" },
        reviewCount: 0,
        types: ["Sports"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    },
    {
        name: "Sphinx International Art Festival",
        imageUrl: "https://th.bing.com/th/id/OIP.FnWHWpV-TVwF-j7L93KkrQHaE1?rs=1&pid=ImgDetMain",
        description: "The Sphinx International Art Festival in Cairo, Egypt, is an annual event that showcases contemporary art from local and international artists. The festival includes exhibitions, workshops, and performances, promoting cultural exchange and artistic expression.",
        date: "2024-04-05",
        coordinates: { latitude: 30.0444, longitude: 31.2357 },
        rating: 5,
        location: { city: "Cairo", country: "Egypt" },
        reviewCount: 0,
        types: ["Festivals"],
        duration: ">3hr",
        suitability: ["Family-Friendly", "Outdoor"],
        reviews: []
    }
];

const sampleAttractions = [
    {
        name: "Eiffel Tower",
        description: "An iconic symbol of Paris, the Eiffel Tower is a wrought-iron lattice tower located on the Champ de Mars. It was named after the engineer Gustave Eiffel, whose company designed and built the tower. Standing at 324 meters tall, it was the tallest man-made structure in the world until the completion of the Chrysler Building in New York in 1930. The Eiffel Tower offers breathtaking panoramic views of Paris from its three levels, each accessible by elevators and stairs. Visitors can enjoy dining at the 58 Tour Eiffel restaurant on the first floor or the Michelin-starred Le Jules Verne on the second floor. The top-level Champagne Bar offers a unique experience with stunning views. The tower is illuminated every evening with thousands of sparkling lights, making it a must-see landmark for any visitor to the City of Light.",
        imageUrl: "https://th.bing.com/th/id/OIP.AW_3WtO4mpBHZSZBQ9OQ9QHaE8?rs=1&pid=ImgDetMain",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.8584, longitude: 2.2945 },
        hours: "9:00 AM - 12:00 AM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Date Night", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Statue of Liberty",
        description: "A colossal neoclassical sculpture on Liberty Island in New York Harbor. It symbolizes freedom and democracy and offers guided tours, a museum, and breathtaking views of the Manhattan skyline.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Statue_of_Liberty%2C_NY.jpg",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.6892, longitude: -74.0445 },
        hours: "8:30 AM - 4:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Great Wall of China",
        description: "An ancient series of walls and fortifications, totaling more than 13,000 miles in length. It offers a glimpse into China's history and provides stunning views of the surrounding landscape.",
        imageUrl: "https://th.bing.com/th/id/R.de59b7f01de4e17486da0adc98f3fdb6?rik=4obrvzWP0xphJw&riu=http%3a%2f%2f3.bp.blogspot.com%2f-v9diPO29Q98%2fUoii64OJDVI%2fAAAAAAAAQxo%2f6g1-qidob2w%2fs1600%2fgreat%2bwall%2bof%2bchina%2b(5).jpg&ehk=qTNFE6FvCeYi6XQjy947taofvTX%2bNSv03iPoQ5T6gBs%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Beijing", country: "China" },
        coordinates: { latitude: 40.4319, longitude: 116.5704 },
        hours: "7:30 AM - 5:30 PM",
        duration: ">3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Colosseum",
        description: "An ancient amphitheater in Rome, Italy, and one of the greatest works of Roman architecture and engineering. It offers guided tours that delve into the history of gladiatorial games and Roman public spectacles.",
        imageUrl: "https://th.bing.com/th/id/OIP.dIMt0mbEgPzVM3rIn3oC5QAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Rome", country: "Italy" },
        coordinates: { latitude: 41.8902, longitude: 12.4922 },
        hours: "8:30 AM - 7:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Machu Picchu",
        description: "An Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley. It is renowned for its sophisticated dry-stone construction and panoramic views.",
        imageUrl: "https://media.cntraveler.com/photos/5818a486b6f3d25e7b5c6a3e/master/pass/GettyImages-573103543.jpg",
        location: { city: "Cusco", country: "Peru" },
        coordinates: { latitude: -13.1631, longitude: -72.5450 },
        hours: "6:00 AM - 5:30 PM",
        duration: ">3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Taj Mahal",
        description: "An ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra. It was commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favorite wife, Mumtaz Mahal.",
        imageUrl: "https://th.bing.com/th/id/OIP.df-SyosYRmFfujaRm9vKEAHaG2?rs=1&pid=ImgDetMain",
        location: { city: "Agra", country: "India" },
        coordinates: { latitude: 27.1751, longitude: 78.0421 },
        hours: "6:00 AM - 6:30 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Christ the Redeemer",
        description: "An Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil. It is 30 meters tall and its arms stretch 28 meters wide. The statue has become an icon of Rio and Brazil.",
        imageUrl: "https://th.bing.com/th/id/R.d1244d62c4a1d998e1f0ec283a7bc687?rik=b6sT%2bKszFF%2fnMA&riu=http%3a%2f%2fstatic.thousandwonders.net%2fChrist.the.Redeemer.original.2544.jpg&ehk=ClRu6WQFql2u3OcH34GpDzSNAxEs9oUyAUJc7XUTe%2f8%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Rio de Janeiro", country: "Brazil" },
        coordinates: { latitude: -22.9519, longitude: -43.2105 },
        hours: "8:00 AM - 7:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Louvre Museum",
        description: "The world's largest art museum and a historic monument in Paris, France. It is home to thousands of works of art, including the Mona Lisa and the Venus de Milo.",
        imageUrl: "https://th.bing.com/th/id/R.1ab32f8db931d045d5224c172d20cdcf?rik=VS59MzR0MfCPog&pid=ImgRaw&r=0",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.8606, longitude: 2.3376 },
        hours: "9:00 AM - 6:00 PM",
        duration: "1-3hr",
        types: ["Museums"],
        suitability: ["Rainy Day", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Golden Gate Bridge",
        description: "A suspension bridge spanning the Golden Gate, the one-mile-wide strait connecting San Francisco Bay and the Pacific Ocean. It is an internationally recognized symbol of San Francisco, California, and the United States.",
        imageUrl: "https://th.bing.com/th/id/R.6a93ef21f7d00b1e4bba531adb2ee90e?rik=N8%2f0EyocjXr8Ig&riu=http%3a%2f%2fwww.urbansplatter.com%2fwp-content%2fuploads%2f2014%2f05%2fGolden-gate-bridge-sunset.jpg&ehk=sN7kyY6I4Gnba%2blVuQS6UQE8utSBXVdjSr%2f0%2be58y2c%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "San Francisco", country: "USA" },
        coordinates: { latitude: 37.8199, longitude: -122.4783 },
        hours: "24 hours",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Sydney Opera House",
        description: "A multi-venue performing arts centre in Sydney, Australia. Designed by Danish architect Jørn Utzon, it is one of the 20th century's most famous and distinctive buildings.",
        imageUrl: "https://th.bing.com/th/id/OIP.D-YzDTUpCXrzbV2YoDHjKgHaFj?rs=1&pid=ImgDetMain",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.8568, longitude: 151.2153 },
        hours: "9:00 AM - 5:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Date Night", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Niagara Falls",
        description: "Three waterfalls that straddle the international border between the Canadian province of Ontario and the US state of New York. They form the southern end of the Niagara Gorge.",
        imageUrl: "https://th.bing.com/th/id/R.b19af00d4317cee02828378abdfd8922?rik=SkZQK1mJf%2fMmRQ&riu=http%3a%2f%2fwww.wallpaperbetter.com%2fwallpaper%2f711%2f960%2f53%2fawesome-niagara-falls-hi-res-images-2K-wallpaper.jpg&ehk=%2fsIj9NhgkfXof9R9isPKS4uwR3H1qejCFakhGSOfSwY%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Niagara Falls", country: "Canada/USA" },
        coordinates: { latitude: 43.0962, longitude: -79.0377 },
        hours: "24 hours",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Santorini",
        description: "An island in the southern Aegean Sea, about 200 km southeast of Greece's mainland. It is known for its stunning sunsets, white-washed houses, and crystal-clear waters.",
        imageUrl: "https://sothebysrealty.gr/wp-content/uploads/2016/11/Santorini-sunset-at-dawn-Greece-Sothebys-International-Realty.jpg",
        location: { city: "Santorini", country: "Greece" },
        coordinates: { latitude: 36.3932, longitude: 25.4615 },
        hours: "24 hours",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Date Night", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Acropolis of Athens",
        description: "An ancient citadel located on a rocky outcrop above the city of Athens. It contains the remains of several ancient buildings of great architectural and historic significance, the most famous being the Parthenon.",
        imageUrl: "https://images.musement.com/cover/0004/59/thumb_358124_cover_header.jpeg?&q=60&fit=crop",
        location: { city: "Athens", country: "Greece" },
        coordinates: { latitude: 37.9715, longitude: 23.7257 },
        hours: "8:00 AM - 8:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "The British Museum",
        description: "A public institution dedicated to human history, art, and culture in London. Its permanent collection of eight million works is among the largest and most comprehensive in existence, originating from all continents.",
        imageUrl: "https://th.bing.com/th/id/R.e1b5a2460034012d259fae5bef5a0853?rik=1NgBNABwk%2fBimQ&riu=http%3a%2f%2flondontopia.net%2fwp-content%2fuploads%2f2014%2f09%2fBritish-Museum-from-NE-2.jpg&ehk=H80ygnT3OA36Ecg6aEW0efnxCIhegxnLJzQI9EIi9xU%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "London", country: "UK" },
        coordinates: { latitude: 51.5194, longitude: -0.1270 },
        hours: "10:00 AM - 5:30 PM",
        duration: "1-3hr",
        types: ["Museums"],
        suitability: ["Rainy Day", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Sagrada Familia",
        description: "A large unfinished Roman Catholic minor basilica in Barcelona, designed by Antoni Gaudí. It is a UNESCO World Heritage Site and a distinctive symbol of Barcelona.",
        imageUrl: "https://th.bing.com/th/id/OIP.t2QmcbhjYuXPYbbwz4oaewAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Barcelona", country: "Spain" },
        coordinates: { latitude: 41.4036, longitude: 2.1744 },
        hours: "9:00 AM - 6:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Date Night", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Pyramids of Giza",
        description: "The pyramids are the last surviving wonder of the original Seven Wonders of the Ancient World. They are an iconic symbol of Egypt and a testament to ancient engineering.",
        imageUrl: "https://th.bing.com/th/id/OIP.HEX_NEdz-whfW1VdmnLpSQAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Giza", country: "Egypt" },
        coordinates: { latitude: 29.9792, longitude: 31.1342 },
        hours: "8:00 AM - 5:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Times Square",
        description: "A major commercial intersection, tourist destination, entertainment center, and neighborhood in Midtown Manhattan. It is brightly adorned with billboards and advertisements and is sometimes referred to as 'The Crossroads of the World'.",
        imageUrl: "https://th.bing.com/th/id/OIP.qDxBDKeI32L0kh7lIMUZbgHaE6?rs=1&pid=ImgDetMain",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.7580, longitude: -73.9855 },
        hours: "24 hours",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Walt Disney World Resort",
        description: "An entertainment complex in Bay Lake and Lake Buena Vista, Florida, near Orlando. It is the flagship destination of Disney's worldwide corporate enterprise and the most visited vacation resort in the world.",
        imageUrl: "https://th.bing.com/th/id/OIP.8XhPzIx7sJB_MJycH8pBFQHaEL?rs=1&pid=ImgDetMain",
        location: { city: "Orlando", country: "USA" },
        coordinates: { latitude: 28.3772, longitude: -81.5707 },
        hours: "8:00 AM - 12:00 AM",
        duration: ">3hr",
        types: ["Amusement Parks"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Grand Canyon",
        description: "A steep-sided canyon carved by the Colorado River in Arizona, United States. The Grand Canyon is 277 miles long, up to 18 miles wide and attains a depth of over a mile.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/03/Grand_Canyon_NP-Arizona-USA.jpg",
        location: { city: "Arizona", country: "USA" },
        coordinates: { latitude: 36.1069, longitude: -112.1129 },
        hours: "24 hours",
        duration: ">3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Mount Fuji",
        description: "An active stratovolcano and the highest mountain in Japan. It is a cultural icon of Japan and is frequently depicted in art and photography, as well as visited by sightseers and climbers.",
        imageUrl: "https://th.bing.com/th/id/OIP.wIFembgBTONDbH5VBphtbwHaE7?rs=1&pid=ImgDetMain",
        location: { city: "Honshu", country: "Japan" },
        coordinates: { latitude: 35.3606, longitude: 138.7274 },
        hours: "24 hours",
        duration: ">3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Alhambra",
        description: "A palace and fortress complex located in Granada, Andalusia, Spain. It is a masterpiece of Moorish architecture and one of Spain's major tourist attractions.",
        imageUrl: "https://th.bing.com/th/id/R.7f2660da542c65857b55f9f9a35ff471?rik=b12GXfV3BSRZVQ&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f2%2f22%2fDetail_Charles_V_palace_Alhambra_Granada_Spain.jpg&ehk=rd2bHc0tAlTlbAD796cT5JpEY2lrFxFl47TsLO1CrWQ%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Granada", country: "Spain" },
        coordinates: { latitude: 37.1761, longitude: -3.5881 },
        hours: "8:30 AM - 8:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Buckingham Palace",
        description: "The London residence and administrative headquarters of the monarch of the United Kingdom. It is often at the centre of state occasions and royal hospitality.",
        imageUrl: "https://th.bing.com/th/id/OIP.jsQk3u4xKL5MX5bri9H59gHaEK?rs=1&pid=ImgDetMain",
        location: { city: "London", country: "UK" },
        coordinates: { latitude: 51.5014, longitude: -0.1419 },
        hours: "9:30 AM - 4:30 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Chichen Itza",
        description: "A complex of Mayan ruins on Mexico's Yucatán Peninsula. It is one of the most visited archaeological sites in Mexico, with over 2.6 million tourists in 2017.",
        imageUrl: "https://th.bing.com/th/id/OIP.OfgbW2Aby_70hlBObTMR8QHaE7?rs=1&pid=ImgDetMain",
        location: { city: "Yucatán", country: "Mexico" },
        coordinates: { latitude: 20.6843, longitude: -88.5678 },
        hours: "8:00 AM - 4:30 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Burj Khalifa",
        description: "A skyscraper in Dubai, United Arab Emirates, and the tallest structure and building in the world. The building has 163 floors, and visitors can enjoy views from its observation decks on the 124th and 148th floors.",
        imageUrl: "https://th.bing.com/th/id/OIP.e4VIypRTTBzp20L9P-rZ8gHaEo?rs=1&pid=ImgDetMain",
        location: { city: "Dubai", country: "UAE" },
        coordinates: { latitude: 25.1972, longitude: 55.2744 },
        hours: "8:00 AM - 12:00 AM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Date Night", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Universal Studios",
        description: "A film studio and theme park in the San Fernando Valley area of Los Angeles County, California. It is one of the oldest and most famous Hollywood film studios still in use.",
        imageUrl: "https://th.bing.com/th/id/OIP.Gx-NAYLCndtKsiCALfkeRQAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Los Angeles", country: "USA" },
        coordinates: { latitude: 34.1381, longitude: -118.3534 },
        hours: "10:00 AM - 6:00 PM",
        duration: ">3hr",
        types: ["Amusement Parks"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "SeaWorld",
        description: "A marine mammal park, oceanarium, and animal theme park in San Diego, California. It is known for its orca, sea lion, and dolphin shows and exhibits.",
        imageUrl: "https://th.bing.com/th/id/OIP.1HjWnWTzvcgFo1sTrqZ6hgHaE8?rs=1&pid=ImgDetMain",
        location: { city: "San Diego", country: "USA" },
        coordinates: { latitude: 32.7654, longitude: -117.2266 },
        hours: "9:00 AM - 6:00 PM",
        duration: ">3hr",
        types: ["Amusement Parks"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Berlin Zoo",
        description: "The most visited zoo in Europe and one of the most popular worldwide. It is home to more than 1,500 species, including pandas, elephants, and gorillas.",
        imageUrl: "https://www.berlin.de/binaries/asset/image_assets/985651/source/1677838306/1000x500/",
        location: { city: "Berlin", country: "Germany" },
        coordinates: { latitude: 52.5085, longitude: 13.3375 },
        hours: "9:00 AM - 6:00 PM",
        duration: "1-3hr",
        types: ["Zoos"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Singapore Zoo",
        description: "A zoological garden in Singapore, known for its 'open' concept. The zoo is home to over 300 species of animals, including a large collection of primates.",
        imageUrl: "https://live.staticflickr.com/20/72296628_32aa3fe17e_b.jpg",
        location: { city: "Singapore", country: "Singapore" },
        coordinates: { latitude: 1.4043, longitude: 103.7930 },
        hours: "8:30 AM - 6:00 PM",
        duration: "1-3hr",
        types: ["Zoos"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    // Paris
    {
        name: "Notre-Dame Cathedral",
        description: "A medieval Catholic cathedral on the Île de la Cité in Paris. It is renowned for its French Gothic architecture, beautiful stained glass windows, and historical significance.",
        imageUrl: "https://th.bing.com/th/id/R.0682dbead14009e0e3dc0e645ad5f82c?rik=aDfee2kYrlGWgQ&pid=ImgRaw&r=0",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.852968, longitude: 2.349902 },
        hours: "8:00 AM - 6:45 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Musée d'Orsay",
        description: "A museum in Paris housed in a former railway station. It holds mainly French art dating from 1848 to 1914, including paintings, sculptures, furniture, and photography.",
        imageUrl: "https://www.tripsavvy.com/thmb/IMFeK3keUE1mqWRBD0HDKtRME_0=/3936x2624/filters:fill(auto,1)/TAM_3375-163e8acb0882471880ae1be9009cfe79.jpg",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.859961, longitude: 2.326561 },
        hours: "9:30 AM - 6:00 PM",
        duration: "1-3hr",
        types: ["Museums"],
        suitability: ["Rainy Day", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Luxembourg Gardens",
        description: "A beautiful public park in Paris. It features formal gardens, statues, fountains, and a large pond where children can sail model boats.",
        imageUrl: "https://th.bing.com/th/id/R.786b0f32343d3f58de275ccb7c47866c?rik=Uaa41cpU2F8%2bNg&riu=http%3a%2f%2fwww.photostocksource.com%2fimages%2ffrance-paris%2f100471034-luxembourg-gardens-lg.jpg&ehk=Q%2bcEW4j8hVyCjlfHtxk45i15245OY33uTUUmeXcsjp8%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.846222, longitude: 2.337160 },
        hours: "7:30 AM - 9:30 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Champs-Élysées",
        description: "One of the most famous avenues in the world, known for its theatres, cafés, and luxury shops. It runs between the Place de la Concorde and the Place Charles de Gaulle, where the Arc de Triomphe is located.",
        imageUrl: "https://th.bing.com/th/id/OIP.utQm-42kydnfNejfLaxMUAHaEK?rs=1&pid=ImgDetMain",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.866867, longitude: 2.311780 },
        hours: "24 hours",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    // Tokyo
    {
        name: "Tokyo Tower",
        description: "A communications and observation tower in the Shiba-koen district of Minato, Tokyo. It is a prominent landmark and tourist destination, offering panoramic views of the city.",
        imageUrl: "https://th.bing.com/th/id/OIP.llpRwKpTfsB52Yg4CNaXogHaE8?rs=1&pid=ImgDetMain",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.658580, longitude: 139.745433 },
        hours: "9:00 AM - 11:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Senso-ji Temple",
        description: "An ancient Buddhist temple located in Asakusa, Tokyo. It is Tokyo's oldest temple and one of its most significant, attracting millions of visitors annually.",
        imageUrl: "https://th.bing.com/th/id/R.faf7cd19eee03660a04be0a706f7ffc0?rik=m6nNcy0oi7CdpQ&pid=ImgRaw&r=0",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.714765, longitude: 139.796655 },
        hours: "6:00 AM - 5:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Ueno Park",
        description: "A spacious public park in the Ueno district of Taito, Tokyo. It is home to museums, a zoo, and cherry blossoms, making it a popular destination for locals and tourists alike.",
        imageUrl: "https://th.bing.com/th/id/R.267394c99424068c3d23547dc738a252?rik=g6qnZNE6vlUfcw&riu=http%3a%2f%2fyouinjapan.net%2ftokyo%2ffoto%2fueno_park.jpg&ehk=%2b4Sg4r6Vrlx3Ac4WTgVZTIJpXRUJGmCzA7EmfY1%2fWa0%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.717226, longitude: 139.770906 },
        hours: "5:00 AM - 11:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Rainy Day"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Akihabara",
        description: "A buzzing shopping hub famed for its electronics retailers, from tiny stalls to vast department stores. It's also a cultural center for anime, manga, and video games.",
        imageUrl: "https://th.bing.com/th/id/OIP.Y63ENOpO1piqXv59cVhtOgAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.698682, longitude: 139.774219 },
        hours: "10:00 AM - 10:00 PM",
        duration: "1-3hr",
        types: ["Fun"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    // New York
    {
        name: "Central Park",
        description: "An urban park in New York City located between the Upper West Side and Upper East Side. It is the fifth-largest park in the city and one of the most visited urban parks in the United States.",
        imageUrl: "https://th.bing.com/th/id/OIP.MNl59pe2GUaBE2fL52k34QHaE7?rs=1&pid=ImgDetMain",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.785091, longitude: -73.968285 },
        hours: "6:00 AM - 1:00 AM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Metropolitan Museum of Art",
        description: "The largest art museum in the United States. Its permanent collection contains over two million works, divided among 17 curatorial departments.",
        imageUrl: "https://th.bing.com/th/id/OIP.VTJX2cc1-NhkRxC7w0b6JQHaE9?rs=1&pid=ImgDetMain",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.779437, longitude: -73.963244 },
        hours: "10:00 AM - 5:30 PM",
        duration: "1-3hr",
        types: ["Museums"],
        suitability: ["Rainy Day", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Brooklyn Bridge",
        description: "A hybrid cable-stayed/suspension bridge in New York City. It connects the boroughs of Manhattan and Brooklyn, spanning the East River.",
        imageUrl: "https://th.bing.com/th/id/OIP.TqjbRHBuvXJMmBoqAdWoSQHaEK?rs=1&pid=ImgDetMain",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.706086, longitude: -73.996864 },
        hours: "24 hours",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "American Museum of Natural History",
        description: "One of the largest natural history museums in the world. It comprises 28 interconnected buildings housing 45 permanent exhibition halls, in addition to a planetarium and a library.",
        imageUrl: "https://th.bing.com/th/id/OIP.VbxtTm6VJrZhy1891i4uCgHaE7?rs=1&pid=ImgDetMain",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.781324, longitude: -73.973988 },
        hours: "10:00 AM - 5:30 PM",
        duration: "1-3hr",
        types: ["Museums"],
        suitability: ["Rainy Day", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    // Sydney
    {
        name: "Bondi Beach",
        description: "A popular beach and the name of the surrounding suburb in Sydney. It is known for its golden sands, surfing, and vibrant atmosphere.",
        imageUrl: "https://th.bing.com/th/id/R.11c3755242d9dcaa0c7ec30342c0e9b0?rik=jSh075nq7pINTQ&pid=ImgRaw&r=0",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.890844, longitude: 151.274292 },
        hours: "24 hours",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Taronga Zoo",
        description: "A major zoo in Sydney, located on the shores of Sydney Harbour. It is home to over 4,000 animals of 350 species, and offers stunning views of the city skyline.",
        imageUrl: "https://th.bing.com/th/id/R.d8c582e54dffef870e283c769616d1d8?rik=uQpDAnif2g3vWg&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f6%2f69%2fTaronga_Zoo_-Sydney%2c_Australia-21March2006.jpg&ehk=6pAYFqNcc95GiJVu1PhEzVtTBQI54nEla3yyA%2b37MPs%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.843000, longitude: 151.241000 },
        hours: "9:30 AM - 5:00 PM",
        duration: "1-3hr",
        types: ["Zoos"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Royal Botanic Garden",
        description: "A major botanical garden located in the heart of Sydney. It offers a tranquil escape from the city's hustle and bustle, with beautifully landscaped gardens and a variety of plant species.",
        imageUrl: "https://th.bing.com/th?id=OIF.vSxouyx2zzMG%2fEMjVIxhfg&rs=1&pid=ImgDetMain",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.864167, longitude: 151.216667 },
        hours: "7:00 AM - 8:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Art Gallery of New South Wales",
        description: "A major public gallery in Sydney. It is one of the largest art museums in Australia, featuring an extensive collection of Australian, European, and Asian art.",
        imageUrl: "https://th.bing.com/th/id/OIP.9xPhVD8m6fJxAUNzQNaDogHaFK?rs=1&pid=ImgDetMain",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.868611, longitude: 151.217222 },
        hours: "10:00 AM - 5:00 PM",
        duration: "1-3hr",
        types: ["Museums"],
        suitability: ["Rainy Day", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    // Cairo
    {
        name: "Egyptian Museum",
        description: "Home to an extensive collection of ancient Egyptian antiquities. It houses the world's largest collection of Pharaonic antiquities and many treasures of King Tutankhamun.",
        imageUrl: "https://th.bing.com/th/id/OIP.wJfe-G41zWrPjn4C8-uWrQHaE7?rs=1&pid=ImgDetMain",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0478, longitude: 31.2336 },
        hours: "9:00 AM - 7:00 PM",
        duration: "1-3hr",
        types: ["Museums"],
        suitability: ["Rainy Day", "Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Al-Azhar Park",
        description: "A public park in Cairo developed by the Aga Khan Trust for Culture. It offers stunning views of the city, green spaces, and a respite from the bustling urban environment.",
        imageUrl: "https://th.bing.com/th/id/R.f5d619a5894ef6353fb45aee8b5a1b02?rik=vFzYwm4cxhq9dQ&pid=ImgRaw&r=0",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0423, longitude: 31.2627 },
        hours: "9:00 AM - 10:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Khan El Khalili",
        description: "A major souk in the historic center of Islamic Cairo. It is a famous bazaar district, known for its traditional crafts, souvenirs, and vibrant atmosphere.",
        imageUrl: "https://literarytoursegypt.com/wp-content/uploads/2022/08/Khan-El-Khalili-Bazaar.jpg",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0477, longitude: 31.2626 },
        hours: "9:00 AM - 11:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families", "Date Night"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Citadel of Saladin",
        description: "A medieval Islamic fortification in Cairo. It was built by Salah ad-Din and offers panoramic views of Cairo along with its mosques and museums.",
        imageUrl: "https://th.bing.com/th/id/OIP.H0ZDPi2RpfvwiPdhfzQBfAHaFg?rs=1&pid=ImgDetMain",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0299, longitude: 31.2613 },
        hours: "9:00 AM - 4:00 PM",
        duration: "1-3hr",
        types: ["Sights"],
        suitability: ["Families"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    }
];

const sampleRestaurants = [
    // Existing Restaurants with updated descriptions and review counts
    {
        name: "Le Meurice",
        description: "A high-end restaurant offering an elegant dining experience in Paris. Known for its exceptional French cuisine and luxurious setting.",
        imageUrl: "https://i.pinimg.com/originals/d6/dc/00/d6dc0052f5c528b0ff4f3fa215d47ec0.jpg",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.8656, longitude: 2.3266 },
        hours: "12:00 PM - 2:30 PM, 7:00 PM - 10:30 PM",
        types: ["French"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Joe's Pizza",
        description: "Famous for its authentic New York-style pizza, Joe's Pizza has been a Greenwich Village institution since it was founded by Pino 'Joe' Pozzuoli in 1975. Located in the heart of Manhattan, this pizzeria is renowned for its classic, thin-crust slices that embody the quintessential New York pizza experience. The unassuming and cozy atmosphere of Joe's Pizza has made it a favorite among locals and tourists alike. Over the decades, it has been featured in numerous films, TV shows, and food documentaries. Each slice is made with fresh ingredients, from the homemade tomato sauce to the perfectly melted mozzarella cheese. Whether you prefer a plain cheese slice or one loaded with pepperoni, Joe's Pizza delivers a consistently delicious and satisfying meal. It's a perfect spot for a quick bite or a late-night snack, staying open until midnight.",
        imageUrl: "https://th.bing.com/th/id/R.069ba508d4f0ca847357b18cda1724fa?rik=jJbjylXRJr9uSw&pid=ImgRaw&r=0",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.7306, longitude: -74.0027 },
        hours: "11:00 AM - 12:00 AM",
        types: ["Pizza", "Casual Dining"],
        priceRange: "$",
        dietaryOptions: ["Vegetarian"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Osteria Francescana",
        description: "A three-Michelin-star restaurant owned and run by chef Massimo Bottura in Modena, Italy. Known for its innovative Italian dishes.",
        imageUrl: "https://th.bing.com/th/id/OIP.eonccao8CnFtKGiMWOwVNwHaEo?rs=1&pid=ImgDetMain",
        location: { city: "Modena", country: "Italy" },
        coordinates: { latitude: 44.6458, longitude: 10.9257 },
        hours: "12:30 PM - 2:30 PM, 7:30 PM - 10:00 PM",
        types: ["Italian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Nobu",
        description: "A high-end sushi restaurant with a stylish setting and a celebrity following. Famous for its innovative Japanese cuisine.",
        imageUrl: "https://th.bing.com/th/id/OIP.T5YV0u4mbXReVC9HsPF7NwHaE8?rs=1&pid=ImgDetMain",
        location: { city: "Los Angeles", country: "USA" },
        coordinates: { latitude: 34.0522, longitude: -118.2437 },
        hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:30 PM",
        types: ["Japanese"],
        priceRange: "$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Peking Duck House",
        description: "Specializing in Peking duck and other traditional Chinese dishes. Known for its authentic flavors and welcoming ambiance.",
        imageUrl: "https://th.bing.com/th/id/R.7c58b136285c377b0a9c274b6d3647f1?rik=KwV54%2bZ2uPbAvw&pid=ImgRaw&r=0",
        location: { city: "Beijing", country: "China" },
        coordinates: { latitude: 39.9042, longitude: 116.4074 },
        hours: "11:00 AM - 10:00 PM",
        types: ["Chinese"],
        priceRange: "$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "El Celler de Can Roca",
        description: "A restaurant in Girona, Catalonia, Spain, opened in 1986 by the Roca brothers. Known for its avant-garde Spanish cuisine.",
        imageUrl: "https://th.bing.com/th/id/OIP.M5J5Dq2-SRk3QrnosIoZKwAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Girona", country: "Spain" },
        coordinates: { latitude: 41.9831, longitude: 2.8249 },
        hours: "1:00 PM - 3:00 PM, 8:00 PM - 10:00 PM",
        types: ["Spanish"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "The Ledbury",
        description: "A contemporary restaurant in Notting Hill, London, offering modern European cuisine. Famous for its innovative dishes and elegant atmosphere.",
        imageUrl: "https://th.bing.com/th/id/R.7a039ca4b930e107cb39d44cbe694c34?rik=tKPsKi3Ua3U5aw&pid=ImgRaw&r=0",
        location: { city: "London", country: "UK" },
        coordinates: { latitude: 51.5175, longitude: -0.1998 },
        hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:00 PM",
        types: ["European"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Gaggan",
        description: "Innovative Indian cuisine served in an edgy, modern setting in Bangkok. Known for its creative and flavorful dishes.",
        imageUrl: "https://th.bing.com/th/id/R.968810e7b7b5133cdc6efbfb413dda59?rik=av0oOevwlHHNSQ&pid=ImgRaw&r=0",
        location: { city: "Bangkok", country: "Thailand" },
        coordinates: { latitude: 13.7563, longitude: 100.5018 },
        hours: "6:00 PM - 11:00 PM",
        types: ["Indian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "La Taqueria",
        description: "Authentic Mexican tacos and street food in a casual setting. Known for its vibrant flavors and friendly atmosphere.",
        imageUrl: "https://i.pinimg.com/originals/f0/a8/ff/f0a8ff875fcf0f2371b3287d6c7bdffc.jpg",
        location: { city: "Mexico City", country: "Mexico" },
        coordinates: { latitude: 19.4326, longitude: -99.1332 },
        hours: "11:00 AM - 11:00 PM",
        types: ["Mexican"],
        priceRange: "$",
        dietaryOptions: ["Vegetarian", "Vegan"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "The Fat Duck",
        description: "A restaurant in Bray, Berkshire, England, owned by the chef Heston Blumenthal. Known for its experimental cuisine and unique dining experience.",
        imageUrl: "https://th.bing.com/th/id/R.e89d0e1d186ccaea91a80dac586e0dfb?rik=V4v%2b4mFvMov0Ig&pid=ImgRaw&r=0",
        location: { city: "Bray", country: "UK" },
        coordinates: { latitude: 51.5095, longitude: -0.7001 },
        hours: "12:00 PM - 2:30 PM, 7:00 PM - 10:00 PM",
        types: ["British"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Din Tai Fung",
        description: "A Taiwanese restaurant franchise specializing in xiaolongbao (soup dumplings). Known for its high-quality dumplings and casual setting.",
        imageUrl: "https://th.bing.com/th/id/R.53e2b9ff4f602162f1143a44a94982e4?rik=OcSAZQ3za2tVrw&riu=http%3a%2f%2f4.bp.blogspot.com%2f-lvtOTj7sV64%2fU9pqO7XKZoI%2fAAAAAAAAKCM%2f2YmrbALXzLA%2fs1600%2fPhoto%2b01.JPG&ehk=WtrvkiLIoNOSajgBkBpJz8Li6aXgXoM%2fiVExcrh0y6k%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Taipei", country: "Taiwan" },
        coordinates: { latitude: 25.0330, longitude: 121.5654 },
        hours: "10:00 AM - 9:00 PM",
        types: ["Chinese"],
        priceRange: "$$",
        dietaryOptions: ["Vegetarian", "Vegan"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Blue Hill at Stone Barns",
        description: "Farm-to-table dining experience located within the Stone Barns Center for Food & Agriculture. Known for its fresh, seasonal dishes.",
        imageUrl: "https://www.gannett-cdn.com/-mm-/3a8f9af1a909d42ad24aea48523f5797a56700c8/c=0-334-5231-3290/local/-/media/2015/04/02/Westchester/Westchester/635635958895051378-Blue-Hill-at-Stone-Barns-Exterior---Ira-Lippke-photographer.jpg?width=3200&height=1680&fit=crop",
        location: { city: "Pocantico Hills", country: "USA" },
        coordinates: { latitude: 41.1035, longitude: -73.8265 },
        hours: "5:00 PM - 10:00 PM",
        types: ["American"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Chez Panisse",
        description: "A Berkeley, California restaurant, known as one of the inspirations for the style of cooking known as California cuisine. Famous for its locally-sourced, organic ingredients.",
        imageUrl: "https://th.bing.com/th/id/R.f02756f43963533741b912cd4155d0a8?rik=ZekJ4IVJF0s2Mw&pid=ImgRaw&r=0",
        location: { city: "Berkeley", country: "USA" },
        coordinates: { latitude: 37.8796, longitude: -122.2680 },
        hours: "5:00 PM - 10:00 PM",
        types: ["American"],
        priceRange: "$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Noma",
        description: "A two-Michelin-star restaurant run by chef René Redzepi in Copenhagen, Denmark. Known for its innovative New Nordic cuisine.",
        imageUrl: "https://th.bing.com/th/id/OIP.b_ToS-5xSocmw4LP68zE5gHaE8?rs=1&pid=ImgDetMain",
        location: { city: "Copenhagen", country: "Denmark" },
        coordinates: { latitude: 55.6761, longitude: 12.5683 },
        hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:00 PM",
        types: ["Scandinavian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Alinea",
        description: "A restaurant in Chicago, Illinois, offering an innovative molecular gastronomy menu. Known for its unique dining experience and cutting-edge cuisine.",
        imageUrl: "https://th.bing.com/th/id/OIP.WjVzJuUq6HMLqm6jklkfRgHaEM?rs=1&pid=ImgDetMain",
        location: { city: "Chicago", country: "USA" },
        coordinates: { latitude: 41.8781, longitude: -87.6298 },
        hours: "5:00 PM - 10:00 PM",
        types: ["American"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "El Farolito",
        description: "A popular Mexican restaurant known for its burritos and tacos. Famous for its vibrant flavors and casual setting.",
        imageUrl: "https://th.bing.com/th/id/R.fe553dd0fe162b9154e2ae538d01f16e?rik=eG3%2fiRuVZP5a%2fw&pid=ImgRaw&r=0",
        location: { city: "San Francisco", country: "USA" },
        coordinates: { latitude: 37.7749, longitude: -122.4194 },
        hours: "10:00 AM - 2:00 AM",
        types: ["Mexican"],
        priceRange: "$",
        dietaryOptions: ["Vegetarian", "Vegan"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Jiro Sushi",
        description: "An intimate, world-renowned sushi restaurant in Tokyo, owned by Jiro Ono. Known for its meticulously prepared sushi.",
        imageUrl: "https://th.bing.com/th/id/R.8f07565adc90dea7cdec686e433e6c9a?rik=gBbxyHP5SAicSw&pid=ImgRaw&r=0",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.6895, longitude: 139.6917 },
        hours: "11:30 AM - 2:00 PM, 5:30 PM - 9:00 PM",
        types: ["Japanese"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Le Bernardin",
        description: "A French seafood restaurant in New York City, consistently ranked among the best restaurants in the world. Known for its exquisite seafood dishes.",
        imageUrl: "https://th.bing.com/th/id/R.c6feb8b348adbc9829f1244ed9526f1c?rik=6Nn4r8luhB894A&riu=http%3a%2f%2f4.bp.blogspot.com%2f-afmuk7xaI2U%2fUxqVtCvYMvI%2fAAAAAAAAI0I%2fVpEznHYHFOI%2fs1600%2fLe-Bernardin-copy.jpg&ehk=uAGvgKL1a9JPGJz3B8wuje1rQTw60nxLj7hhJyVbjoc%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.7615, longitude: -73.9818 },
        hours: "12:00 PM - 2:30 PM, 5:30 PM - 10:00 PM",
        types: ["French"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "The French Laundry",
        description: "A French restaurant located in Yountville, California, in the Napa Valley. Known for its elegant setting and meticulously prepared dishes.",
        imageUrl: "https://th.bing.com/th/id/OIP.qJROrdvu_7L-fCL_-P6NOwHaE8?rs=1&pid=ImgDetMain",
        location: { city: "Yountville", country: "USA" },
        coordinates: { latitude: 38.4041, longitude: -122.3647 },
        hours: "11:00 AM - 1:00 PM, 5:30 PM - 9:00 PM",
        types: ["French"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Zuma",
        description: "A high-end Japanese restaurant offering contemporary izakaya dining. Known for its stylish setting and modern Japanese dishes.",
        imageUrl: "https://th.bing.com/th/id/R.c04207414199f01e5bb0f7e0cee610c6?rik=c5zgT8FXDVW8MA&pid=ImgRaw&r=0",
        location: { city: "London", country: "UK" },
        coordinates: { latitude: 51.5074, longitude: -0.1278 },
        hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:30 PM",
        types: ["Japanese"],
        priceRange: "$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Gotham Bar & Grill",
        description: "A Michelin-starred restaurant in New York City offering modern American cuisine. Known for its sophisticated dishes and stylish ambiance.",
        imageUrl: "https://th.bing.com/th/id/OIP.16vqcoTxxQdUGv0wneV9NAHaD4?rs=1&pid=ImgDetMain",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.7326, longitude: -73.9935 },
        hours: "12:00 PM - 3:00 PM, 5:00 PM - 11:00 PM",
        types: ["American"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "La Pergola",
        description: "A three-Michelin-star restaurant in Rome offering Mediterranean cuisine. Known for its elegant dining experience and breathtaking views.",
        imageUrl: "https://th.bing.com/th/id/R.2e3e9bebae7d7b197206725c53b704b9?rik=88eM70nHC0wQvA&pid=ImgRaw&r=0",
        location: { city: "Rome", country: "Italy" },
        coordinates: { latitude: 41.9028, longitude: 12.4964 },
        hours: "7:30 PM - 11:30 PM",
        types: ["Italian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Pierre Gagnaire",
        description: "A Michelin three-star restaurant in Paris offering innovative French cuisine. Known for its creative dishes and luxurious setting.",
        imageUrl: "https://i.pinimg.com/736x/4d/06/d0/4d06d0b561cb34579cbabbb6dce8127a--restaurant-design-restaurants.jpg",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.8566, longitude: 2.3522 },
        hours: "12:00 PM - 2:30 PM, 7:30 PM - 10:00 PM",
        types: ["French"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Quintonil",
        description: "A modern Mexican restaurant in Mexico City offering creative cuisine. Known for its innovative dishes and elegant ambiance.",
        imageUrl: "https://th.bing.com/th/id/OIP.TSSgyEvB0iQPxTY_fLEQ_AHaE7?rs=1&pid=ImgDetMain",
        location: { city: "Mexico City", country: "Mexico" },
        coordinates: { latitude: 19.4326, longitude: -99.1332 },
        hours: "1:00 PM - 3:00 PM, 6:00 PM - 11:00 PM",
        types: ["Mexican"],
        priceRange: "$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Eleven Madison Park",
        description: "A contemporary American restaurant in New York City. Known for its innovative dishes and exceptional dining experience.",
        imageUrl: "https://th.bing.com/th/id/R.91993a702241cfde02d2bba52b5da523?rik=EQDxJsPY4uyiYw&pid=ImgRaw&r=0",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.7416, longitude: -73.9872 },
        hours: "12:00 PM - 2:00 PM, 5:30 PM - 10:00 PM",
        types: ["American"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "The Ivy",
        description: "A famous British restaurant known for its celebrity clientele and classic dishes. Known for its elegant setting and exceptional service.",
        imageUrl: "https://th.bing.com/th/id/OIP.zqhpDrAYcOWo_WYT6xizZQHaE7?rs=1&pid=ImgDetMain",
        location: { city: "London", country: "UK" },
        coordinates: { latitude: 51.5112, longitude: -0.1281 },
        hours: "12:00 PM - 11:30 PM",
        types: ["British"],
        priceRange: "$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Tim Ho Wan",
        description: "Known as the world's cheapest Michelin-starred restaurant, offering dim sum. Famous for its high-quality dishes and affordable prices.",
        imageUrl: "https://th.bing.com/th/id/R.8da179dd31595cee9b10e2758f51f4fc?rik=pI6YwpVBhqLEzw&pid=ImgRaw&r=0",
        location: { city: "Hong Kong", country: "China" },
        coordinates: { latitude: 22.3193, longitude: 114.1694 },
        hours: "10:00 AM - 9:00 PM",
        types: ["Chinese"],
        priceRange: "$",
        dietaryOptions: ["Vegetarian", "Vegan"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },

    // New Restaurants for specified cities
    {
        name: "Benoit Paris",
        description: "A classic French bistro in the heart of Paris, offering traditional French dishes with a modern twist.",
        imageUrl: "https://th.bing.com/th/id/R.2d39026edf507a07d7fd1d188017eb72?rik=S7ryZ6NzgX%2b8mQ&riu=http%3a%2f%2fmedia-cdn.tripadvisor.com%2fmedia%2fphoto-s%2f01%2f30%2f49%2f60%2fthe-front-today.jpg&ehk=qk10ECJrEzZiMCT7A0nJ7cAuvwuw8VsyEvDz0Lp4GPQ%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.8610, longitude: 2.3398 },
        hours: "12:00 PM - 2:30 PM, 7:00 PM - 10:30 PM",
        types: ["French"],
        priceRange: "$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Le Jules Verne",
        description: "A Michelin-starred restaurant located on the Eiffel Tower, offering gourmet French cuisine with panoramic views of Paris.",
        imageUrl: "https://axwwgrkdco.cloudimg.io/v7/mtp-cf-images.s3-eu-west-1.amazonaws.com/images/max/350d8fb2-cda0-40f5-a706-6f50870140ac.jpg?width=1000",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.8584, longitude: 2.2945 },
        hours: "12:00 PM - 1:30 PM, 7:00 PM - 9:30 PM",
        types: ["French"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "L'Ambroisie",
        description: "A renowned three-Michelin-star restaurant in Paris, offering exquisite French cuisine in an elegant setting.",
        imageUrl: "https://th.bing.com/th/id/OIP.unjk225OCHAPIqhXdSf2ZgAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Paris", country: "France" },
        coordinates: { latitude: 48.8566, longitude: 2.3522 },
        hours: "12:00 PM - 2:00 PM, 7:30 PM - 10:00 PM",
        types: ["French"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Himitsu Sushi",
        description: "A hidden gem in Tokyo, offering an intimate dining experience with expertly crafted sushi.",
        imageUrl: "https://th.bing.com/th/id/R.e95e193fbaee8dc8f574e7a28ed578a4?rik=yo%2fAudDU9bA66A&riu=http%3a%2f%2fwww.himitsu.com.br%2fimgs%2fsushis_sashimis_500.jpg&ehk=JOFvJNkysFXxl3jTWUmIyp9JosgM%2b82ck4JqSmuVHfo%3d&risl=&pid=ImgRaw&r=0",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.6895, longitude: 139.6917 },
        hours: "12:00 PM - 2:00 PM, 6:00 PM - 10:00 PM",
        types: ["Japanese"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Kaiseki Ichiju",
        description: "A traditional kaiseki restaurant in Tokyo, offering a multi-course meal that highlights seasonal ingredients.",
        imageUrl: "https://tenkujapan.vn/wp-content/uploads/2023/04/Kaiseki-la-gi.jpg",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.6895, longitude: 139.6917 },
        hours: "6:00 PM - 10:00 PM",
        types: ["Japanese"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Tempura Kondo",
        description: "A renowned tempura restaurant in Tokyo, known for its light and crispy tempura made from the freshest ingredients.",
        imageUrl: "https://th.bing.com/th/id/OIP.WKvhF1cs__wD_RsKKv7wVgHaDO?rs=1&pid=ImgDetMain",
        location: { city: "Tokyo", country: "Japan" },
        coordinates: { latitude: 35.6895, longitude: 139.6917 },
        hours: "12:00 PM - 2:00 PM, 5:30 PM - 9:00 PM",
        types: ["Japanese"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Per Se",
        description: "A renowned three-Michelin-star restaurant in New York City, offering French and American cuisine with stunning views of Central Park.",
        imageUrl: "https://th.bing.com/th/id/OIP.SZXIToW42nl--n169HFMMgHaE8?rs=1&pid=ImgDetMain",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.7684, longitude: -73.9831 },
        hours: "12:00 PM - 2:00 PM, 5:30 PM - 10:00 PM",
        types: ["French", "American"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Momofuku Ko",
        description: "An innovative restaurant in New York City, offering a multi-course tasting menu that showcases modern American cuisine.",
        imageUrl: "https://th.bing.com/th/id/R.4b196cc032e0073061b3429e01613fe0?rik=yuSKBYalNuWOQg&pid=ImgRaw&r=0",
        location: { city: "New York", country: "USA" },
        coordinates: { latitude: 40.7295, longitude: -73.9830 },
        hours: "6:00 PM - 10:00 PM",
        types: ["American"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Attica",
        description: "A celebrated restaurant in Melbourne, offering modern Australian cuisine with an emphasis on native ingredients.",
        imageUrl: "https://www.restaurant-ranking.com/uploads/tx_rrrestaurants/restaurants/Attica_Interior_1.jpg",
        location: { city: "Melbourne", country: "Australia" },
        coordinates: { latitude: -37.8142, longitude: 144.9632 },
        hours: "6:00 PM - 11:00 PM",
        types: ["Australian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Quay",
        description: "An iconic restaurant in Sydney, offering modern Australian cuisine with stunning views of Sydney Harbour.",
        imageUrl: "https://th.bing.com/th/id/OIP.fn7nFn3-xNJHDFD6Dqk2sgHaFj?rs=1&pid=ImgDetMain",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.8568, longitude: 151.2153 },
        hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:30 PM",
        types: ["Australian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Bennelong",
        description: "A prestigious restaurant located within the Sydney Opera House, offering contemporary Australian cuisine.",
        imageUrl: "https://th.bing.com/th/id/OIP.f-H6BIYVmskA9lQe1HSYQgHaFS?rs=1&pid=ImgDetMain",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.8568, longitude: 151.2153 },
        hours: "12:00 PM - 3:00 PM, 5:30 PM - 10:00 PM",
        types: ["Australian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Aria",
        description: "A fine dining restaurant in Sydney, offering contemporary Australian cuisine with stunning views of the Sydney Opera House and Harbour Bridge.",
        imageUrl: "https://th.bing.com/th/id/OIP.meYWNfGF79gsZAhWOJ3OTgAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Sydney", country: "Australia" },
        coordinates: { latitude: -33.8568, longitude: 151.2153 },
        hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:30 PM",
        types: ["Australian"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Sequoia",
        description: "A contemporary fine dining restaurant in Cairo, offering a fusion of Mediterranean and Middle Eastern cuisine.",
        imageUrl: "https://th.bing.com/th/id/OIP.IFcUYyETD5yUy92wHGHvegAAAA?rs=1&pid=ImgDetMain",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0444, longitude: 31.2357 },
        hours: "12:00 PM - 12:00 AM",
        types: ["Mediterranean", "Middle Eastern"],
        priceRange: "$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Zooba",
        description: "A popular restaurant in Cairo, offering traditional Egyptian street food with a modern twist.",
        imageUrl: "https://www.tasteandflavors.com/wp-content/uploads/2022/05/zooba.jpg",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0444, longitude: 31.2357 },
        hours: "8:00 AM - 12:00 AM",
        types: ["Egyptian"],
        priceRange: "$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Abou El Sid",
        description: "A well-known restaurant in Cairo, offering authentic Egyptian cuisine in a traditional setting.",
        imageUrl: "https://cdn.tasteatlas.com/images/restaurants/66b5d4e72c084813829a70f0e565ea88.jpg?mw=1300",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0444, longitude: 31.2357 },
        hours: "12:00 PM - 1:00 AM",
        types: ["Egyptian"],
        priceRange: "$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    },
    {
        name: "Kazoku",
        description: "A contemporary Japanese restaurant in Cairo, known for its sushi and other traditional Japanese dishes.",
        imageUrl: "https://th.bing.com/th/id/R.f95d70c7066b143ab6678e8712b1807e?rik=3PYd6fTZiS0zmQ&pid=ImgRaw&r=0",
        location: { city: "Cairo", country: "Egypt" },
        coordinates: { latitude: 30.0444, longitude: 31.2357 },
        hours: "1:00 PM - 11:00 PM",
        types: ["Japanese"],
        priceRange: "$$$$",
        dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
        rating: 5,
        reviewCount: 0,
        reviews: []
    }
];

  

mongoose.connect(process.env.MONGO_URL)
  .then(() => {
    console.log('Connected to MongoDB');
    return clearDatabase();
  })
  .then(() => {
    return populateDatabase();
  })
  .catch((err) => {
    console.error('Error connecting to MongoDB', err);
  });

async function clearDatabase() {
  try {
    await Event.deleteMany({});
    await Attraction.deleteMany({});
    await Restaurant.deleteMany({});
    console.log('Database cleared');
  } catch (err) {
    console.error('Error clearing database', err);
  }
}

async function populateDatabase() {
  try {
    await Event.insertMany(sampleEvents);
    await Attraction.insertMany(sampleAttractions);
    await Restaurant.insertMany(sampleRestaurants);
    console.log('Database populated with sample data');
    mongoose.connection.close();
  } catch (err) {
    console.error('Error populating database', err);
    mongoose.connection.close();
  }
}
