const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Event = require('../models/Event');
const Attraction = require('../models/Attraction');
const Restaurant = require('../models/Restaurant');

dotenv.config();

const sampleEvents = [
    {
      name: "Euro 2024",
      imageUrl: "https://trthaberstatic.cdn.wp.trt.com.tr/resimler/1928000/euro-2024-depophotos-1928725.jpg",
      description: "The 2024 UEFA European Football Championship, commonly referred to as Euro 2024.",
      date: "2024-06-14",
      coordinates: { latitude: 52.5200, longitude: 13.4050 },
      rating: 5,
      location: { city: "Berlin", country: "Germany" },
      reviewCount: 200,
      types: ["Sports"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Oktoberfest",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Oktoberfest.jpg",
      description: "World's largest Volksfest held annually in Munich, Germany.",
      date: "2024-09-21",
      coordinates: { latitude: 48.1351, longitude: 11.5820 },
      rating: 5,
      location: { city: "Munich", country: "Germany" },
      reviewCount: 500,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Tokyo Olympics 2024",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Tokyo_2020_logo.svg",
      description: "The Summer Olympic Games in Tokyo, showcasing athletes from around the world.",
      date: "2024-07-26",
      coordinates: { latitude: 35.6895, longitude: 139.6917 },
      rating: 5,
      location: { city: "Tokyo", country: "Japan" },
      reviewCount: 300,
      types: ["Sports"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Coachella 2024",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/66/Coachella_logo.png",
      description: "Annual music and arts festival held in California.",
      date: "2024-04-12",
      coordinates: { latitude: 33.6803, longitude: -116.1739 },
      rating: 5,
      location: { city: "Indio", country: "USA" },
      reviewCount: 1000,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Carnival of Venice",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Venezia_-_Carnevale.jpg",
      description: "Annual festival held in Venice, Italy, known for its elaborate masks.",
      date: "2024-02-08",
      coordinates: { latitude: 45.4408, longitude: 12.3155 },
      rating: 5,
      location: { city: "Venice", country: "Italy" },
      reviewCount: 450,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Edinburgh Festival Fringe",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Edinburgh_Festival_Fringe_logo.svg",
      description: "The world's largest arts festival held annually in Edinburgh, Scotland.",
      date: "2024-08-02",
      coordinates: { latitude: 55.9533, longitude: -3.1883 },
      rating: 5,
      location: { city: "Edinburgh", country: "UK" },
      reviewCount: 600,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Burning Man",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Burning_Man_logo.svg",
      description: "Annual event in the western United States at Black Rock City.",
      date: "2024-08-25",
      coordinates: { latitude: 40.7864, longitude: -119.2065 },
      rating: 5,
      location: { city: "Black Rock City", country: "USA" },
      reviewCount: 700,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Day of the Dead",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/D%C3%ADa_de_Muertos.jpg",
      description: "A Mexican holiday where families remember and honor their deceased loved ones.",
      date: "2024-11-01",
      coordinates: { latitude: 19.4326, longitude: -99.1332 },
      rating: 5,
      location: { city: "Mexico City", country: "Mexico" },
      reviewCount: 400,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Mardi Gras",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Mardi_Gras.jpg",
      description: "A festival held before Lent, known for parades and masquerade balls.",
      date: "2024-02-13",
      coordinates: { latitude: 29.9511, longitude: -90.0715 },
      rating: 5,
      location: { city: "New Orleans", country: "USA" },
      reviewCount: 350,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Glastonbury Festival",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Glastonbury_logo.svg",
      description: "A five-day festival of contemporary performing arts in Somerset, England.",
      date: "2024-06-26",
      coordinates: { latitude: 51.1839, longitude: -2.5866 },
      rating: 5,
      location: { city: "Pilton", country: "UK" },
      reviewCount: 800,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "SXSW",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/SXSW_2018_logo.svg",
      description: "Annual conglomerate of film, interactive media, and music festivals and conferences.",
      date: "2024-03-08",
      coordinates: { latitude: 30.2672, longitude: -97.7431 },
      rating: 5,
      location: { city: "Austin", country: "USA" },
      reviewCount: 500,
      types: ["Conferences"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "La Tomatina",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/10/Tomatina.jpg",
      description: "Annual Spanish festival where participants throw tomatoes at each other.",
      date: "2024-08-28",
      coordinates: { latitude: 39.4920, longitude: -0.4191 },
      rating: 5,
      location: { city: "Buñol", country: "Spain" },
      reviewCount: 250,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Holi Festival",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Holi_festival.jpg",
      description: "The Hindu festival of colors, celebrated in India and Nepal.",
      date: "2024-03-20",
      coordinates: { latitude: 28.6139, longitude: 77.2090 },
      rating: 5,
      location: { city: "Delhi", country: "India" },
      reviewCount: 600,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Cannes Film Festival",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/39/Festival_de_Cannes_Logo.png",
      description: "Annual film festival held in Cannes, France.",
      date: "2024-05-14",
      coordinates: { latitude: 43.5528, longitude: 7.0174 },
      rating: 5,
      location: { city: "Cannes", country: "France" },
      reviewCount: 300,
      types: ["Conferences"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Sundance Film Festival",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Sundance_Film_Festival_2012.jpg",
      description: "Annual film festival organized by the Sundance Institute.",
      date: "2024-01-18",
      coordinates: { latitude: 40.6461, longitude: -111.4980 },
      rating: 5,
      location: { city: "Park City", country: "USA" },
      reviewCount: 400,
      types: ["Conferences"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Jazz Fest",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Jazz_Fest_2014.jpg",
      description: "Annual celebration of the unique music and culture of New Orleans and Louisiana.",
      date: "2024-04-26",
      coordinates: { latitude: 29.9511, longitude: -90.0715 },
      rating: 5,
      location: { city: "New Orleans", country: "USA" },
      reviewCount: 500,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Tomorrowland",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Tomorrowland_2012.jpg",
      description: "Annual electronic dance music festival held in Belgium.",
      date: "2024-07-19",
      coordinates: { latitude: 51.0936, longitude: 4.3911 },
      rating: 5,
      location: { city: "Boom", country: "Belgium" },
      reviewCount: 1000,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Diwali",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Diwali_lights.jpg",
      description: "The Hindu festival of lights, celebrated every autumn.",
      date: "2024-11-03",
      coordinates: { latitude: 28.6139, longitude: 77.2090 },
      rating: 5,
      location: { city: "Delhi", country: "India" },
      reviewCount: 700,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Chinese New Year",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Chinese_New_Year_2016.jpg",
      description: "The festival that celebrates the beginning of a new year on the traditional lunisolar Chinese calendar.",
      date: "2024-02-10",
      coordinates: { latitude: 39.9042, longitude: 116.4074 },
      rating: 5,
      location: { city: "Beijing", country: "China" },
      reviewCount: 500,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Comic-Con",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Comic-Con_2015.jpg",
      description: "Annual comic book convention held in San Diego, California.",
      date: "2024-07-18",
      coordinates: { latitude: 32.7157, longitude: -117.1611 },
      rating: 5,
      location: { city: "San Diego", country: "USA" },
      reviewCount: 800,
      types: ["Conferences"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Indoor"],
      reviews: []
    },
    {
      name: "Wimbledon",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Wimbledon_tennis_courts.jpg",
      description: "The oldest tennis tournament in the world, held in Wimbledon, London.",
      date: "2024-06-24",
      coordinates: { latitude: 51.4344, longitude: -0.2145 },
      rating: 5,
      location: { city: "London", country: "UK" },
      reviewCount: 600,
      types: ["Sports"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Rio Carnival",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Carnaval2004.jpg",
      description: "The world's largest carnival, held before Lent in Rio de Janeiro, Brazil.",
      date: "2024-02-16",
      coordinates: { latitude: -22.9068, longitude: -43.1729 },
      rating: 5,
      location: { city: "Rio de Janeiro", country: "Brazil" },
      reviewCount: 1000,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Lollapalooza",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Lollapalooza_2015.jpg",
      description: "Annual music festival featuring a wide variety of music genres.",
      date: "2024-08-01",
      coordinates: { latitude: 41.8758, longitude: -87.6186 },
      rating: 5,
      location: { city: "Chicago", country: "USA" },
      reviewCount: 900,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "St. Patrick's Day Parade",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/St._Patrick%27s_Day_parade_in_Dublin.jpg",
      description: "A cultural and religious celebration held on 17 March, the traditional death date of Saint Patrick.",
      date: "2024-03-17",
      coordinates: { latitude: 53.3498, longitude: -6.2603 },
      rating: 5,
      location: { city: "Dublin", country: "Ireland" },
      reviewCount: 300,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "The Kentucky Derby",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/95/Kentucky_Derby.jpg",
      description: "A Grade I stakes race for three-year-old Thoroughbreds, held annually in Louisville, Kentucky.",
      date: "2024-05-04",
      coordinates: { latitude: 38.2026, longitude: -85.7713 },
      rating: 5,
      location: { city: "Louisville", country: "USA" },
      reviewCount: 450,
      types: ["Sports"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Thanksgiving Day Parade",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/Macy%27s_Thanksgiving_Day_Parade_2018.jpg",
      description: "Annual parade presented by Macy's, held in New York City.",
      date: "2024-11-28",
      coordinates: { latitude: 40.7128, longitude: -74.0060 },
      rating: 5,
      location: { city: "New York", country: "USA" },
      reviewCount: 550,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Running of the Bulls",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Sanfermines-Pamplona.jpg",
      description: "Annual event in which bulls are run through the streets of Pamplona, Spain.",
      date: "2024-07-07",
      coordinates: { latitude: 42.8169, longitude: -1.6432 },
      rating: 5,
      location: { city: "Pamplona", country: "Spain" },
      reviewCount: 350,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Oktoberfest in Munich",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Oktoberfest_M%C3%BCnchen.JPG",
      description: "World's largest Volksfest held annually in Munich, Germany.",
      date: "2024-09-21",
      coordinates: { latitude: 48.1351, longitude: 11.5820 },
      rating: 5,
      location: { city: "Munich", country: "Germany" },
      reviewCount: 700,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Albuquerque International Balloon Fiesta",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Albuquerque_Balloon_Fiesta_2013.jpg",
      description: "Annual hot air balloon festival that takes place in Albuquerque, New Mexico.",
      date: "2024-10-05",
      coordinates: { latitude: 35.0844, longitude: -106.6504 },
      rating: 5,
      location: { city: "Albuquerque", country: "USA" },
      reviewCount: 300,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Gion Matsuri",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/Gion_Matsuri_2010.jpg",
      description: "An annual festival in Kyoto and is one of the most famous festivals in Japan.",
      date: "2024-07-01",
      coordinates: { latitude: 35.0116, longitude: 135.7681 },
      rating: 5,
      location: { city: "Kyoto", country: "Japan" },
      reviewCount: 400,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    },
    {
      name: "Diwali in India",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/Diwali_lamps.jpg",
      description: "Festival of Lights celebrated by millions of Hindus, Sikhs, and Jains across the world.",
      date: "2024-11-12",
      coordinates: { latitude: 28.6139, longitude: 77.2090 },
      rating: 5,
      location: { city: "Delhi", country: "India" },
      reviewCount: 600,
      types: ["Festivals"],
      duration: ">3hr",
      suitability: ["Family-Friendly", "Outdoor"],
      reviews: []
    }
  ];
  

  const sampleAttractions = [
    {
      name: "Eiffel Tower",
      description: "An iconic symbol of Paris, offering panoramic views of the city.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg",
      location: { city: "Paris", country: "France" },
      coordinates: { latitude: 48.8584, longitude: 2.2945 },
      hours: "9:00 AM - 12:00 AM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Date Night", "Families"],
      rating: 5,
      reviewCount: 1000,
      reviews: []
    },
    {
      name: "Statue of Liberty",
      description: "A colossal neoclassical sculpture on Liberty Island in New York Harbor.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Statue_of_Liberty_7.jpg",
      location: { city: "New York", country: "USA" },
      coordinates: { latitude: 40.6892, longitude: -74.0445 },
      hours: "8:30 AM - 4:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 4.5,
      reviewCount: 800,
      reviews: []
    },
    {
      name: "Great Wall of China",
      description: "Ancient series of walls and fortifications, totaling more than 13,000 miles in length.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Mutianyu_Great_Wall.jpg",
      location: { city: "Beijing", country: "China" },
      coordinates: { latitude: 40.4319, longitude: 116.5704 },
      hours: "7:30 AM - 5:30 PM",
      duration: ">3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 900,
      reviews: []
    },
    {
      name: "Colosseum",
      description: "An ancient amphitheater in Rome, Italy, and one of the greatest works of Roman architecture and engineering.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg",
      location: { city: "Rome", country: "Italy" },
      coordinates: { latitude: 41.8902, longitude: 12.4922 },
      hours: "8:30 AM - 7:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 850,
      reviews: []
    },
    {
      name: "Machu Picchu",
      description: "An Incan citadel set high in the Andes Mountains in Peru, above the Urubamba River valley.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Machu_Picchu%2C_Peru.jpg",
      location: { city: "Cusco", country: "Peru" },
      coordinates: { latitude: -13.1631, longitude: -72.5450 },
      hours: "6:00 AM - 5:30 PM",
      duration: ">3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 750,
      reviews: []
    },
    {
      name: "Taj Mahal",
      description: "An ivory-white marble mausoleum on the south bank of the Yamuna river in the Indian city of Agra.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/Taj-Mahal.jpg",
      location: { city: "Agra", country: "India" },
      coordinates: { latitude: 27.1751, longitude: 78.0421 },
      hours: "6:00 AM - 6:30 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 800,
      reviews: []
    },
    {
      name: "Christ the Redeemer",
      description: "An Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Christ_the_Redeemer_statue.jpg",
      location: { city: "Rio de Janeiro", country: "Brazil" },
      coordinates: { latitude: -22.9519, longitude: -43.2105 },
      hours: "8:00 AM - 7:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 650,
      reviews: []
    },
    {
      name: "Louvre Museum",
      description: "The world's largest art museum and a historic monument in Paris, France.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Louvre_Museum_Wikimedia_Commons.jpg",
      location: { city: "Paris", country: "France" },
      coordinates: { latitude: 48.8606, longitude: 2.3376 },
      hours: "9:00 AM - 6:00 PM",
      duration: "1-3hr",
      types: ["Museums"],
      suitability: ["Rainy Day", "Families"],
      rating: 5,
      reviewCount: 1200,
      reviews: []
    },
    {
      name: "Golden Gate Bridge",
      description: "A suspension bridge spanning the Golden Gate, the one-mile-wide strait connecting San Francisco Bay and the Pacific Ocean.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0c/GoldenGateBridge-001.jpg",
      location: { city: "San Francisco", country: "USA" },
      coordinates: { latitude: 37.8199, longitude: -122.4783 },
      hours: "24 hours",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 950,
      reviews: []
    },
    {
      name: "Sydney Opera House",
      description: "A multi-venue performing arts centre in Sydney, Australia.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Sydney_Opera_House_-_Dec_2008.jpg",
      location: { city: "Sydney", country: "Australia" },
      coordinates: { latitude: -33.8568, longitude: 151.2153 },
      hours: "9:00 AM - 5:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Date Night", "Families"],
      rating: 5,
      reviewCount: 700,
      reviews: []
    },
    {
      name: "Niagara Falls",
      description: "Three waterfalls that straddle the international border between the Canadian province of Ontario and the US state of New York.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/16/Niagara_Falls_from_Prospect_Point.jpg",
      location: { city: "Niagara Falls", country: "Canada/USA" },
      coordinates: { latitude: 43.0962, longitude: -79.0377 },
      hours: "24 hours",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 1100,
      reviews: []
    },
    {
      name: "Santorini",
      description: "An island in the southern Aegean Sea, about 200 km southeast of Greece's mainland.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Santorini_Thira_Fira_01.jpg",
      location: { city: "Santorini", country: "Greece" },
      coordinates: { latitude: 36.3932, longitude: 25.4615 },
      hours: "24 hours",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Date Night", "Families"],
      rating: 5,
      reviewCount: 950,
      reviews: []
    },
    {
      name: "Acropolis of Athens",
      description: "An ancient citadel located on a rocky outcrop above the city of Athens.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Acropolis_of_Athens_2015.jpg",
      location: { city: "Athens", country: "Greece" },
      coordinates: { latitude: 37.9715, longitude: 23.7257 },
      hours: "8:00 AM - 8:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 800,
      reviews: []
    },
    {
      name: "The British Museum",
      description: "A public institution dedicated to human history, art, and culture in London.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/47/British_Museum_from_NE_2.JPG",
      location: { city: "London", country: "UK" },
      coordinates: { latitude: 51.5194, longitude: -0.1270 },
      hours: "10:00 AM - 5:30 PM",
      duration: "1-3hr",
      types: ["Museums"],
      suitability: ["Rainy Day", "Families"],
      rating: 5,
      reviewCount: 1200,
      reviews: []
    },
    {
      name: "The Louvre",
      description: "The world's largest art museum and a historic monument in Paris, France.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/61/Louvre_Museum_Wikimedia_Commons.jpg",
      location: { city: "Paris", country: "France" },
      coordinates: { latitude: 48.8606, longitude: 2.3376 },
      hours: "9:00 AM - 6:00 PM",
      duration: "1-3hr",
      types: ["Museums"],
      suitability: ["Rainy Day", "Families"],
      rating: 5,
      reviewCount: 1200,
      reviews: []
    },
    {
      name: "Sagrada Familia",
      description: "A large unfinished Roman Catholic minor basilica in Barcelona, designed by Antoni Gaudí.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Sagrada_Familia_2021.jpg",
      location: { city: "Barcelona", country: "Spain" },
      coordinates: { latitude: 41.4036, longitude: 2.1744 },
      hours: "9:00 AM - 6:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Date Night", "Families"],
      rating: 5,
      reviewCount: 1100,
      reviews: []
    },
    {
      name: "Pyramids of Giza",
      description: "The pyramids are the last surviving wonder of the original Seven Wonders of the Ancient World.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Kheops-Pyramid.jpg",
      location: { city: "Giza", country: "Egypt" },
      coordinates: { latitude: 29.9792, longitude: 31.1342 },
      hours: "8:00 AM - 5:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 1300,
      reviews: []
    },
    {
      name: "Times Square",
      description: "A major commercial intersection, tourist destination, entertainment center, and neighborhood in Midtown Manhattan.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Times_Square%2C_New_York_City_%28HDR%29.jpg",
      location: { city: "New York", country: "USA" },
      coordinates: { latitude: 40.7580, longitude: -73.9855 },
      hours: "24 hours",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 1400,
      reviews: []
    },
    {
      name: "Walt Disney World Resort",
      description: "An entertainment complex in Bay Lake and Lake Buena Vista, Florida.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Cinderella_Castle_at_Magic_Kingdom.JPG",
      location: { city: "Orlando", country: "USA" },
      coordinates: { latitude: 28.3772, longitude: -81.5707 },
      hours: "8:00 AM - 12:00 AM",
      duration: ">3hr",
      types: ["Amusement Parks"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 2000,
      reviews: []
    },
    {
      name: "Grand Canyon",
      description: "A steep-sided canyon carved by the Colorado River in Arizona, United States.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/af/Grand_Canyon_view_from_Pima_Point_2010.jpg",
      location: { city: "Arizona", country: "USA" },
      coordinates: { latitude: 36.1069, longitude: -112.1129 },
      hours: "24 hours",
      duration: ">3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 1800,
      reviews: []
    },
    {
      name: "Mount Fuji",
      description: "An active stratovolcano and the highest mountain in Japan.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/12/Mount_Fuji_from_Yamanaka.jpg",
      location: { city: "Honshu", country: "Japan" },
      coordinates: { latitude: 35.3606, longitude: 138.7274 },
      hours: "24 hours",
      duration: ">3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 1000,
      reviews: []
    },
    {
      name: "Alhambra",
      description: "A palace and fortress complex located in Granada, Andalusia, Spain.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Alhambra_oeste.JPG",
      location: { city: "Granada", country: "Spain" },
      coordinates: { latitude: 37.1761, longitude: -3.5881 },
      hours: "8:30 AM - 8:00 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 700,
      reviews: []
    },
    {
      name: "Buckingham Palace",
      description: "The London residence and administrative headquarters of the monarch of the United Kingdom.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/69/Buckingham_Palace%2C_London_-_April_2009.jpg",
      location: { city: "London", country: "UK" },
      coordinates: { latitude: 51.5014, longitude: -0.1419 },
      hours: "9:30 AM - 4:30 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 600,
      reviews: []
    },
    {
      name: "Chichen Itza",
      description: "A complex of Mayan ruins on Mexico's Yucatán Peninsula.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Chichen_Itza_3.jpg",
      location: { city: "Yucatán", country: "Mexico" },
      coordinates: { latitude: 20.6843, longitude: -88.5678 },
      hours: "8:00 AM - 4:30 PM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 800,
      reviews: []
    },
    {
      name: "Burj Khalifa",
      description: "A skyscraper in Dubai, United Arab Emirates, and the tallest structure and building in the world.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Burj_Khalifa.jpg",
      location: { city: "Dubai", country: "UAE" },
      coordinates: { latitude: 25.1972, longitude: 55.2744 },
      hours: "8:00 AM - 12:00 AM",
      duration: "1-3hr",
      types: ["Sights"],
      suitability: ["Date Night", "Families"],
      rating: 5,
      reviewCount: 1000,
      reviews: []
    },
    {
      name: "Universal Studios",
      description: "A film studio and theme park in the San Fernando Valley area of Los Angeles County, California.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Universal_Studios_entrance.jpg",
      location: { city: "Los Angeles", country: "USA" },
      coordinates: { latitude: 34.1381, longitude: -118.3534 },
      hours: "10:00 AM - 6:00 PM",
      duration: ">3hr",
      types: ["Amusement Parks"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 1300,
      reviews: []
    },
    {
      name: "SeaWorld",
      description: "A marine mammal park, oceanarium, and animal theme park in San Diego, California.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/62/SeaWorld_San_Diego_-_Journey_to_Atlantis.jpg",
      location: { city: "San Diego", country: "USA" },
      coordinates: { latitude: 32.7654, longitude: -117.2266 },
      hours: "9:00 AM - 6:00 PM",
      duration: ">3hr",
      types: ["Amusement Parks"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 1100,
      reviews: []
    },
    {
      name: "Berlin Zoo",
      description: "The most visited zoo in Europe and one of the most popular worldwide.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/44/Berlin_Zoo_entrance.jpg",
      location: { city: "Berlin", country: "Germany" },
      coordinates: { latitude: 52.5085, longitude: 13.3375 },
      hours: "9:00 AM - 6:00 PM",
      duration: "1-3hr",
      types: ["Zoos"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 900,
      reviews: []
    },
    {
      name: "Singapore Zoo",
      description: "A zoological garden in Singapore, known for its 'open' concept.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Singapore_Zoo_-_entrance_2012.jpg",
      location: { city: "Singapore", country: "Singapore" },
      coordinates: { latitude: 1.4043, longitude: 103.7930 },
      hours: "8:30 AM - 6:00 PM",
      duration: "1-3hr",
      types: ["Zoos"],
      suitability: ["Families"],
      rating: 5,
      reviewCount: 950,
      reviews: []
    },
    {
      name: "Spa at the Ritz-Carlton",
      description: "A luxurious spa offering a range of treatments and therapies.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Spa_at_Ritz-Carlton.jpg",
      location: { city: "New York", country: "USA" },
      coordinates: { latitude: 40.7128, longitude: -74.0060 },
      hours: "9:00 AM - 9:00 PM",
      duration: "1-3hr",
      types: ["Spas"],
      suitability: ["Date Night"],
      rating: 5,
      reviewCount: 800,
      reviews: []
    }
  ];
  

  const sampleRestaurants = [
    {
      name: "Le Meurice",
      description: "A high-end restaurant offering an elegant dining experience in Paris.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Le_Meurice.jpg",
      location: { city: "Paris", country: "France" },
      coordinates: { latitude: 48.8656, longitude: 2.3266 },
      hours: "12:00 PM - 2:30 PM, 7:00 PM - 10:30 PM",
      types: ["French"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 300,
      reviews: []
    },
    {
      name: "Joe's Pizza",
      description: "Famous for its New York-style pizza, located in the heart of Manhattan.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Joes_Pizza.jpg",
      location: { city: "New York", country: "USA" },
      coordinates: { latitude: 40.7306, longitude: -74.0027 },
      hours: "11:00 AM - 12:00 AM",
      types: ["Pizza", "Casual Dining"],
      priceRange: "$",
      dietaryOptions: ["Vegetarian"],
      rating: 4.8,
      reviewCount: 500,
      reviews: []
    },
    {
      name: "Osteria Francescana",
      description: "A three-Michelin-star restaurant owned and run by chef Massimo Bottura in Modena, Italy.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Osteria_Francescana.jpg",
      location: { city: "Modena", country: "Italy" },
      coordinates: { latitude: 44.6458, longitude: 10.9257 },
      hours: "12:30 PM - 2:30 PM, 7:30 PM - 10:00 PM",
      types: ["Italian"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 400,
      reviews: []
    },
    {
      name: "Nobu",
      description: "A high-end sushi restaurant with a stylish setting and a celebrity following.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Nobu_Restaurant.jpg",
      location: { city: "Los Angeles", country: "USA" },
      coordinates: { latitude: 34.0522, longitude: -118.2437 },
      hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:30 PM",
      types: ["Japanese"],
      priceRange: "$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.7,
      reviewCount: 450,
      reviews: []
    },
    {
      name: "Peking Duck House",
      description: "Specializing in Peking duck and other traditional Chinese dishes.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Peking_Duck_House.jpg",
      location: { city: "Beijing", country: "China" },
      coordinates: { latitude: 39.9042, longitude: 116.4074 },
      hours: "11:00 AM - 10:00 PM",
      types: ["Chinese"],
      priceRange: "$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.5,
      reviewCount: 350,
      reviews: []
    },
    {
      name: "El Celler de Can Roca",
      description: "A restaurant in Girona, Catalonia, Spain, opened in 1986 by the Roca brothers.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/El_Celler_de_Can_Roca.jpg",
      location: { city: "Girona", country: "Spain" },
      coordinates: { latitude: 41.9831, longitude: 2.8249 },
      hours: "1:00 PM - 3:00 PM, 8:00 PM - 10:00 PM",
      types: ["Spanish"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 600,
      reviews: []
    },
    {
      name: "The Ledbury",
      description: "A contemporary restaurant in Notting Hill, London, offering modern European cuisine.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e5/The_Ledbury.jpg",
      location: { city: "London", country: "UK" },
      coordinates: { latitude: 51.5175, longitude: -0.1998 },
      hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:00 PM",
      types: ["European"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.9,
      reviewCount: 550,
      reviews: []
    },
    {
      name: "Gaggan",
      description: "Innovative Indian cuisine served in an edgy, modern setting in Bangkok.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Gaggan_Restaurant.jpg",
      location: { city: "Bangkok", country: "Thailand" },
      coordinates: { latitude: 13.7563, longitude: 100.5018 },
      hours: "6:00 PM - 11:00 PM",
      types: ["Indian"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.8,
      reviewCount: 600,
      reviews: []
    },
    {
      name: "La Taqueria",
      description: "Authentic Mexican tacos and street food in a casual setting.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/73/La_Taqueria.jpg",
      location: { city: "Mexico City", country: "Mexico" },
      coordinates: { latitude: 19.4326, longitude: -99.1332 },
      hours: "11:00 AM - 11:00 PM",
      types: ["Mexican"],
      priceRange: "$",
      dietaryOptions: ["Vegetarian", "Vegan"],
      rating: 4.6,
      reviewCount: 300,
      reviews: []
    },
    {
      name: "The Fat Duck",
      description: "A restaurant in Bray, Berkshire, England, owned by the chef Heston Blumenthal.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/The_Fat_Duck.jpg",
      location: { city: "Bray", country: "UK" },
      coordinates: { latitude: 51.5095, longitude: -0.7001 },
      hours: "12:00 PM - 2:30 PM, 7:00 PM - 10:00 PM",
      types: ["British"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 450,
      reviews: []
    },
    {
      name: "Din Tai Fung",
      description: "A Taiwanese restaurant franchise specializing in xiaolongbao (soup dumplings).",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/85/Din_Tai_Fung_Restaurant.jpg",
      location: { city: "Taipei", country: "Taiwan" },
      coordinates: { latitude: 25.0330, longitude: 121.5654 },
      hours: "10:00 AM - 9:00 PM",
      types: ["Chinese"],
      priceRange: "$$",
      dietaryOptions: ["Vegetarian", "Vegan"],
      rating: 4.8,
      reviewCount: 500,
      reviews: []
    },
    {
      name: "Blue Hill at Stone Barns",
      description: "Farm-to-table dining experience located within the Stone Barns Center for Food & Agriculture.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Blue_Hill_at_Stone_Barns.jpg",
      location: { city: "Pocantico Hills", country: "USA" },
      coordinates: { latitude: 41.1035, longitude: -73.8265 },
      hours: "5:00 PM - 10:00 PM",
      types: ["American"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.9,
      reviewCount: 350,
      reviews: []
    },
    {
      name: "Chez Panisse",
      description: "A Berkeley, California restaurant, known as one of the inspirations for the style of cooking known as California cuisine.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Chez_Panisse.jpg",
      location: { city: "Berkeley", country: "USA" },
      coordinates: { latitude: 37.8796, longitude: -122.2680 },
      hours: "5:00 PM - 10:00 PM",
      types: ["American"],
      priceRange: "$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.7,
      reviewCount: 400,
      reviews: []
    },
    {
      name: "Noma",
      description: "A two-Michelin-star restaurant run by chef René Redzepi in Copenhagen, Denmark.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Noma_Restaurant.jpg",
      location: { city: "Copenhagen", country: "Denmark" },
      coordinates: { latitude: 55.6761, longitude: 12.5683 },
      hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:00 PM",
      types: ["Scandinavian"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 600,
      reviews: []
    },
    {
      name: "Alinea",
      description: "A restaurant in Chicago, Illinois, offering an innovative molecular gastronomy menu.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Alinea_Restaurant.jpg",
      location: { city: "Chicago", country: "USA" },
      coordinates: { latitude: 41.8781, longitude: -87.6298 },
      hours: "5:00 PM - 10:00 PM",
      types: ["American"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.9,
      reviewCount: 500,
      reviews: []
    },
    {
      name: "El Farolito",
      description: "A popular Mexican restaurant known for its burritos and tacos.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c8/El_Farolito.jpg",
      location: { city: "San Francisco", country: "USA" },
      coordinates: { latitude: 37.7749, longitude: -122.4194 },
      hours: "10:00 AM - 2:00 AM",
      types: ["Mexican"],
      priceRange: "$",
      dietaryOptions: ["Vegetarian", "Vegan"],
      rating: 4.5,
      reviewCount: 400,
      reviews: []
    },
    {
      name: "Jiro Sushi",
      description: "An intimate, world-renowned sushi restaurant in Tokyo, owned by Jiro Ono.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/47/Jiro_Sushi.jpg",
      location: { city: "Tokyo", country: "Japan" },
      coordinates: { latitude: 35.6895, longitude: 139.6917 },
      hours: "11:30 AM - 2:00 PM, 5:30 PM - 9:00 PM",
      types: ["Japanese"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 300,
      reviews: []
    },
    {
      name: "Le Bernardin",
      description: "A French seafood restaurant in New York City, consistently ranked among the best restaurants in the world.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Le_Bernardin.jpg",
      location: { city: "New York", country: "USA" },
      coordinates: { latitude: 40.7615, longitude: -73.9818 },
      hours: "12:00 PM - 2:30 PM, 5:30 PM - 10:00 PM",
      types: ["French"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.9,
      reviewCount: 450,
      reviews: []
    },
    {
      name: "The French Laundry",
      description: "A French restaurant located in Yountville, California, in the Napa Valley.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5d/The_French_Laundry.jpg",
      location: { city: "Yountville", country: "USA" },
      coordinates: { latitude: 38.4041, longitude: -122.3647 },
      hours: "11:00 AM - 1:00 PM, 5:30 PM - 9:00 PM",
      types: ["French"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 500,
      reviews: []
    },
    {
      name: "Zuma",
      description: "A high-end Japanese restaurant offering contemporary izakaya dining.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/85/Zuma_Restaurant.jpg",
      location: { city: "London", country: "UK" },
      coordinates: { latitude: 51.5074, longitude: -0.1278 },
      hours: "12:00 PM - 2:30 PM, 6:00 PM - 10:30 PM",
      types: ["Japanese"],
      priceRange: "$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.8,
      reviewCount: 300,
      reviews: []
    },
    {
      name: "Gotham Bar & Grill",
      description: "A Michelin-starred restaurant in New York City offering modern American cuisine.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Gotham_Bar_%26_Grill.jpg",
      location: { city: "New York", country: "USA" },
      coordinates: { latitude: 40.7326, longitude: -73.9935 },
      hours: "12:00 PM - 3:00 PM, 5:00 PM - 11:00 PM",
      types: ["American"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.7,
      reviewCount: 400,
      reviews: []
    },
    {
      name: "La Pergola",
      description: "A three-Michelin-star restaurant in Rome offering Mediterranean cuisine.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/La_Pergola.jpg",
      location: { city: "Rome", country: "Italy" },
      coordinates: { latitude: 41.9028, longitude: 12.4964 },
      hours: "7:30 PM - 11:30 PM",
      types: ["Italian"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 350,
      reviews: []
    },
    {
      name: "Pierre Gagnaire",
      description: "A Michelin three-star restaurant in Paris offering innovative French cuisine.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Pierre_Gagnaire.jpg",
      location: { city: "Paris", country: "France" },
      coordinates: { latitude: 48.8566, longitude: 2.3522 },
      hours: "12:00 PM - 2:30 PM, 7:30 PM - 10:00 PM",
      types: ["French"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 400,
      reviews: []
    },
    {
      name: "Quintonil",
      description: "A modern Mexican restaurant in Mexico City offering creative cuisine.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Quintonil.jpg",
      location: { city: "Mexico City", country: "Mexico" },
      coordinates: { latitude: 19.4326, longitude: -99.1332 },
      hours: "1:00 PM - 3:00 PM, 6:00 PM - 11:00 PM",
      types: ["Mexican"],
      priceRange: "$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.8,
      reviewCount: 300,
      reviews: []
    },
    {
      name: "Eleven Madison Park",
      description: "A contemporary American restaurant in New York City.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Eleven_Madison_Park.jpg",
      location: { city: "New York", country: "USA" },
      coordinates: { latitude: 40.7416, longitude: -73.9872 },
      hours: "12:00 PM - 2:00 PM, 5:30 PM - 10:00 PM",
      types: ["American"],
      priceRange: "$$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 5,
      reviewCount: 500,
      reviews: []
    },
    {
      name: "The Ivy",
      description: "A famous British restaurant known for its celebrity clientele and classic dishes.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7a/The_Ivy_London.jpg",
      location: { city: "London", country: "UK" },
      coordinates: { latitude: 51.5112, longitude: -0.1281 },
      hours: "12:00 PM - 11:30 PM",
      types: ["British"],
      priceRange: "$$$",
      dietaryOptions: ["Vegetarian", "Vegan", "Gluten-Free"],
      rating: 4.6,
      reviewCount: 450,
      reviews: []
    },
    {
      name: "Tim Ho Wan",
      description: "Known as the world's cheapest Michelin-starred restaurant, offering dim sum.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/71/Tim_Ho_Wan.jpg",
      location: { city: "Hong Kong", country: "China" },
      coordinates: { latitude: 22.3193, longitude: 114.1694 },
      hours: "10:00 AM - 9:00 PM",
      types: ["Chinese"],
      priceRange: "$",
      dietaryOptions: ["Vegetarian", "Vegan"],
      rating: 4.7,
      reviewCount: 350,
      reviews: []
    }
  ];
  

mongoose.connect(process.env.MONGO_URL)
  .then(() => {
    console.log('Connected to MongoDB');
    return clearDatabase();
  })
  .then(() => {
    return populateDatabase();
  })
  .catch((err) => {
    console.error('Error connecting to MongoDB', err);
  });

async function clearDatabase() {
  try {
    await Event.deleteMany({});
    await Attraction.deleteMany({});
    await Restaurant.deleteMany({});
    console.log('Database cleared');
  } catch (err) {
    console.error('Error clearing database', err);
  }
}

async function populateDatabase() {
  try {
    await Event.insertMany(sampleEvents);
    await Attraction.insertMany(sampleAttractions);
    await Restaurant.insertMany(sampleRestaurants);
    console.log('Database populated with sample data');
    mongoose.connection.close();
  } catch (err) {
    console.error('Error populating database', err);
    mongoose.connection.close();
  }
}
